/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { VerbData } from './types';

export const VERBS_DATA: Record<string, VerbData> = {
  amar: {
    verbo: 'amar',
    infinitivoEs: 'amar',
    infinitivoHy: 'սիրել',
    tipoEs: 'Regular',
    tipoHy: 'Կանոնավոր',
    conjugacionEs: 'Primera (-ar)',
    conjugacionHy: 'Առաջին (-ar)',
    noPersonales: [
      { nombreEs: 'Infinitivo simple', nombreHy: 'Պարզ անորոշ ձև', forma: 'amar' },
      { nombreEs: 'Gerundio simple', nombreHy: 'Պարզ գերունդիո', forma: 'amando' },
      { nombreEs: 'Participio', nombreHy: 'Դերբայ (Participio)', forma: 'amado' },
      { nombreEs: 'Infinitivo compuesto', nombreHy: 'Բաղադրյալ անորոշ ձև', forma: 'haber amado' },
      { nombreEs: 'Gerundio compuesto', nombreHy: 'Բաղադրյալ գերունդիո', forma: 'habiendo amado' },
    ],
    tiempos: [
      // INDICATIVO SIMPLES
      {
        id: 'amar_ind_pres',
        nombreEs: 'Presente de indicativo',
        nombreHy: 'Սահմանական ներկա',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Expresa acciones habituales, situaciones actuales y verdades generales.',
        descripcionHy: 'Արտահայտում է սովորական գործողություններ, ներկա իրավիճակներ և ընդհանուր ճշմարտություններ։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amo', analisis: { lexema: 'am-', vocalTematica: 'Ø', desinencia: '-o' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amas', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-s' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'ama', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: 'Ø' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amamos', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amáis', analisis: { lexema: 'am-', vocalTematica: '-á-', desinencia: '-is' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'aman', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-n' } },
        ],
      },
      {
        id: 'amar_ind_imp',
        nombreEs: 'Pretérito imperfecto de indicativo',
        nombreHy: 'Սահմանական անկատար անցյալ',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Expresa acciones habituales o en desarrollo en el pasado (-ba-).',
        descripcionHy: 'Արտահայտում է անցյալի սովորություններ կամ տևական գործողություններ (-ba-)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amaba', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ba-', desinencia: 'Ø' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amabas', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ba-', desinencia: '-s' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amaba', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ba-', desinencia: 'Ø' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amábamos', analisis: { lexema: 'am-', vocalTematica: '-á-', tiempoModo: '-ba-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amabais', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ba-', desinencia: '-is' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amaban', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ba-', desinencia: '-n' } },
        ],
      },
      {
        id: 'amar_ind_perf_simple',
        nombreEs: 'Pretérito perfecto simple (indefinido)',
        nombreHy: 'Սահմանական ավարտված անցյալ (indefinido)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Presenta una acción pasada como concluida en un punto definido.',
        descripcionHy: 'Անցյալ գործողությունը ներկայացնում է որպես ավարտված որոշակի պահին։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amé', analisis: { lexema: 'am-', desinencia: '-é' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amaste', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-ste' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amó', analisis: { lexema: 'am-', desinencia: '-ó' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amamos', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amasteis', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-steis' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amaron', analisis: { lexema: 'am-', vocalTematica: '-a-', desinencia: '-ron' } },
        ],
      },
      {
        id: 'amar_ind_fut',
        nombreEs: 'Futuro simple de indicativo',
        nombreHy: 'Սահմանական պարզ ապառնի',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Expresa una acción futura. Se forma sobre el infinitivo con terminaciones acentuadas.',
        descripcionHy: 'Արտահայտում է ապագա գործողություն։ Կազմվում է անորոշ ձևի հիման վրա շեշտված վերջավորություններով։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amaré', analisis: { lexema: 'amar-', desinencia: '-é' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amarás', analisis: { lexema: 'amar-', desinencia: '-ás' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amará', analisis: { lexema: 'amar-', desinencia: '-á' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amaremos', analisis: { lexema: 'amar-', desinencia: '-emos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amaréis', analisis: { lexema: 'amar-', desinencia: '-éis' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amarán', analisis: { lexema: 'amar-', desinencia: '-án' } },
        ],
      },
      {
        id: 'amar_ind_cond',
        nombreEs: 'Condicional simple de indicativo',
        nombreHy: 'Սահմանական պարզ պայմանական',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Acción hipotética o futuro del pasado. Terminaciones con tilde en la -í-.',
        descripcionHy: 'Ենթադրական գործողություն կամ ապագան անցյալի տեսանկյունից։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amaría', analisis: { lexema: 'amar-', desinencia: '-ía' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amarías', analisis: { lexema: 'amar-', desinencia: '-ías' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amaría', analisis: { lexema: 'amar-', desinencia: '-ía' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amaríamos', analisis: { lexema: 'amar-', desinencia: '-íamos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amaríais', analisis: { lexema: 'amar-', desinencia: '-íais' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amarían', analisis: { lexema: 'amar-', desinencia: '-ían' } },
        ],
      },
      // INDICATIVO COMPUESTOS
      {
        id: 'amar_ind_perf_comp',
        nombreEs: 'Pretérito perfecto compuesto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ներկա (he amado)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'Acción pasada conectada con el presente (he + amado).',
        descripcionHy: 'Ներկայի հետ կապ ունեցող անցյալ գործողություն (he + amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'he amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'has amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'ha amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hemos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habéis amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'han amado' },
        ],
      },
      {
        id: 'amar_ind_plusc',
        nombreEs: 'Pretérito pluscuamperfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար անցյալ (había amado)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'Acción anterior a otra situación del pasado (había + amado).',
        descripcionHy: 'Այլ անցյալից առաջ ավարտված գործողություն (había + amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'había amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habías amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'había amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habíamos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habíais amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habían amado' },
        ],
      },
      {
        id: 'amar_ind_ant',
        nombreEs: 'Pretérito anterior de indicativo',
        nombreHy: 'Սահմանական հարակատար անցյալ (hube amado)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'Acción inmediatamente anterior a otra pasada (hube + amado). Uso literario.',
        descripcionHy: 'Մեկ այլ անցյալին անմիջապես նախորդած գործողություն (hube + amado)։ Գրական ոճ։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hube amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubiste amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubo amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubimos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubisteis amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieron amado' },
        ],
      },
      {
        id: 'amar_ind_fut_perf',
        nombreEs: 'Futuro perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ապառնի (habré amado)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'Acción que habrá concluido antes de un momento futuro (habré + amado).',
        descripcionHy: 'Ապագայի որոշակի պահից առաջ ավարտված գործողություն (habré + amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habré amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrás amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habrá amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habremos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habréis amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrán amado' },
        ],
      },
      {
        id: 'amar_ind_cond_perf',
        nombreEs: 'Condicional perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար պայմանական (habría amado)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'Acción que habría ocurrido si se hubiera cumplido una condición (habría + amado).',
        descripcionHy: 'Գործողություն, որը տեղի կունենար անցյալում պայմանի դեպքում (habría + amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habría amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrías amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habría amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habríamos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habríais amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrían amado' },
        ],
      },
      // SUBJUNTIVO SIMPLES
      {
        id: 'amar_sub_pres',
        nombreEs: 'Presente de subjuntivo',
        nombreHy: 'Ըղձական ներկա',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'Expresa deseo, hipótesis o duda en el presente/futuro. Vocal opuesta: -e-.',
        descripcionHy: 'Արտահայտում է ցանկություն, ենթադրություն կամ կասկած։ 1-ին խոնարհման համար՝ -e-։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'ame', analisis: { lexema: 'am-', vocalTematica: '-e-', desinencia: 'Ø' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'ames', analisis: { lexema: 'am-', vocalTematica: '-e-', desinencia: '-s' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'ame', analisis: { lexema: 'am-', vocalTematica: '-e-', desinencia: 'Ø' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amemos', analisis: { lexema: 'am-', vocalTematica: '-e-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'améis', analisis: { lexema: 'am-', vocalTematica: '-é-', desinencia: '-is' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amen', analisis: { lexema: 'am-', vocalTematica: '-e-', desinencia: '-n' } },
        ],
      },
      {
        id: 'amar_sub_imp_ra',
        nombreEs: 'Pretérito imperfecto de subjuntivo (serie -ra)',
        nombreHy: 'Ըղձական անկատար անցյալ (-ra շարք)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'Primera serie con terminación -ra. Totalmente equivalente a -se.',
        descripcionHy: '-ra վերջավորությամբ առաջին շարքը։ Լիովին համարժեք է -se շարքին։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amara', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ra-', desinencia: 'Ø' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amaras', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ra-', desinencia: '-s' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amara', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ra-', desinencia: 'Ø' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amáramos', analisis: { lexema: 'am-', vocalTematica: '-á-', tiempoModo: '-ra-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amarais', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ra-', desinencia: '-is' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amaran', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-ra-', desinencia: '-n' } },
        ],
      },
      {
        id: 'amar_sub_imp_se',
        nombreEs: 'Pretérito imperfecto de subjuntivo (serie -se)',
        nombreHy: 'Ըղձական անկատար անցյալ (-se շարք)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'Segunda serie con terminación -se. Mismo valor que la serie -ra.',
        descripcionHy: '-se վերջավորությամբ երկրորդ շարքը։ Ունի նույն քերականական արժեքը։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amase', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-se-', desinencia: 'Ø' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amases', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-se-', desinencia: '-s' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amase', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-se-', desinencia: 'Ø' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amásemos', analisis: { lexema: 'am-', vocalTematica: '-á-', tiempoModo: '-se-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amaseis', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-se-', desinencia: '-is' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amasen', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-se-', desinencia: '-n' } },
        ],
      },
      {
        id: 'amar_sub_fut',
        nombreEs: 'Futuro simple de subjuntivo',
        nombreHy: 'Ըղձական պարզ ապառնի',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'Poco usado en lengua viva. ¡No confundir con el futuro de indicativo amaré!',
        descripcionHy: 'Այժմ հազվադեպ է գործածվում։ Չշփոթել սահմանական amaré ձևի հետ։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'amare', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-re-', desinencia: 'Ø' } },
          { personaEs: 'tú', personaHy: 'դու', forma: 'amares', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-re-', desinencia: '-s' } },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'amare', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-re-', desinencia: 'Ø' } },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'amáremos', analisis: { lexema: 'am-', vocalTematica: '-á-', tiempoModo: '-re-', desinencia: '-mos' } },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'amareis', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-re-', desinencia: '-is' } },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'amaren', analisis: { lexema: 'am-', vocalTematica: '-a-', tiempoModo: '-re-', desinencia: '-n' } },
        ],
      },
      // SUBJUNTIVO COMPUESTOS
      {
        id: 'amar_sub_perf_comp',
        nombreEs: 'Pretérito perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ներկա (haya amado)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'Acción terminada con repercusión presente valorada subjetivamente (haya amado).',
        descripcionHy: 'Ներկայից գնահատվող ավարտված գործողություն (haya amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'haya amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hayas amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'haya amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hayamos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hayáis amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hayan amado' },
        ],
      },
      {
        id: 'amar_sub_plusc_ra',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiera amado)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'Acción hipotética o condición pasada no cumplida (hubiera amado).',
        descripcionHy: 'Անցյալի չիրականացած պայման (hubiera amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiera amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieras amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiera amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéramos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubierais amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieran amado' },
        ],
      },
      {
        id: 'amar_sub_plusc_se',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiese amado)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'Variante equivalente con hubiese (hubiese amado).',
        descripcionHy: 'Համարժեք տարբերակ hubiese-ով (hubiese amado)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiese amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieses amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiese amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiésemos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubieseis amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubiesen amado' },
        ],
      },
      {
        id: 'amar_sub_fut_perf',
        nombreEs: 'Futuro perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ապառնի (hubiere amado)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'Estructura arcaizante / jurídica: hubiere + amado.',
        descripcionHy: 'Հնաոճ/իրավական կառուցվածք՝ hubiere + amado։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiere amado' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieres amado' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiere amado' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéremos amado' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubiereis amado' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieren amado' },
        ],
      },
      // IMPERATIVO
      {
        id: 'amar_imperativo',
        nombreEs: 'Imperativo (afirmativo y negativo)',
        nombreHy: 'Հրամայական եղանակ (հաստատական և ժխտական)',
        tiempoTipo: 'simple',
        modo: 'imperativo',
        descripcionEs: 'Formas directas: tú (ama), vosotros (amad). Negativo con presente subjuntivo.',
        descripcionHy: 'Ուղիղ ձևեր՝ tú (ama), vosotros (amad)։ Ժխտականը՝ ըղձականով։',
        formas: [
          { personaEs: 'tú (afirmativo)', personaHy: 'դու (հաստատական)', forma: 'ama' },
          { personaEs: 'usted (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'ame' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք (հաստատական)', forma: 'amemos' },
          { personaEs: 'vosotros / vosotras (afirmativo)', personaHy: 'դուք (հաստատական)', forma: 'amad' },
          { personaEs: 'ustedes (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'amen' },
          { personaEs: 'tú (negativo)', personaHy: 'դու (ժխտական)', forma: 'no ames' },
        ],
      },
    ],
  },

  temer: {
    verbo: 'temer',
    infinitivoEs: 'temer',
    infinitivoHy: 'վախենալ',
    tipoEs: 'Regular',
    tipoHy: 'Կանոնավոր',
    conjugacionEs: 'Segunda (-er)',
    conjugacionHy: 'Երկրորդ (-er)',
    noPersonales: [
      { nombreEs: 'Infinitivo simple', nombreHy: 'Պարզ անորոշ ձև', forma: 'temer' },
      { nombreEs: 'Gerundio simple', nombreHy: 'Պարզ գերունդիո', forma: 'temiendo' },
      { nombreEs: 'Participio', nombreHy: 'Դերբայ (Participio)', forma: 'temido' },
      { nombreEs: 'Infinitivo compuesto', nombreHy: 'Բաղադրյալ անորոշ ձև', forma: 'haber temido' },
      { nombreEs: 'Gerundio compuesto', nombreHy: 'Բաղադրյալ գերունդիո', forma: 'habiendo temido' },
    ],
    tiempos: [
      {
        id: 'temer_ind_pres',
        nombreEs: 'Presente de indicativo',
        nombreHy: 'Սահմանական ներկա',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Expresa acciones habituales en el presente de 2.ª conjugación.',
        descripcionHy: '2-րդ խոնարհման սահմանական ներկա ժամանակը։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temo' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temes' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'teme' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'tememos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'teméis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temen' },
        ],
      },
      {
        id: 'temer_ind_imp',
        nombreEs: 'Pretérito imperfecto de indicativo',
        nombreHy: 'Սահմանական անկատար անցյալ (-ía)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Acciones pasadas habituales de 2.ª conjugación con -ía acentuada.',
        descripcionHy: '2-րդ խոնարհման անկատար անցյալը՝ շեշտված -ía վերջավորությամբ։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temía' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temías' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temía' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temíamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temíais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temían' },
        ],
      },
      {
        id: 'temer_ind_perf_simple',
        nombreEs: 'Pretérito perfecto simple (indefinido)',
        nombreHy: 'Սահմանական ավարտված անցյալ (temí)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Acción terminada en el pasado de 2.ª conjugación.',
        descripcionHy: '2-րդ խոնարհման ավարտված անցյալ ժամանակաձևը։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temí' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temiste' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temió' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temimos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temisteis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temieron' },
        ],
      },
      {
        id: 'temer_ind_fut',
        nombreEs: 'Futuro simple de indicativo',
        nombreHy: 'Սահմանական պարզ ապառնի',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Infinitivo temer + -é, -ás, -á, -emos, -éis, -án.',
        descripcionHy: 'Անորոշ temer + ապառնու վերջավորությունները։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temeré' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temerás' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temerá' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temeremos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temeréis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temerán' },
        ],
      },
      {
        id: 'temer_ind_cond',
        nombreEs: 'Condicional simple de indicativo',
        nombreHy: 'Սահմանական պարզ պայմանական',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'temer + -ía, -ías, -ía, -íamos, -íais, -ían.',
        descripcionHy: 'temer + պայմանականի վերջավորությունները։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temería' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temerías' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temería' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temeríamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temeríais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temerían' },
        ],
      },
      // COMPUESTOS INDICATIVO
      {
        id: 'temer_ind_perf_comp',
        nombreEs: 'Pretérito perfecto compuesto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ներկա (he temido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'he, has, ha... + temido',
        descripcionHy: 'he, has, ha... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'he temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'has temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'ha temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hemos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habéis temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'han temido' },
        ],
      },
      {
        id: 'temer_ind_plusc',
        nombreEs: 'Pretérito pluscuamperfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար անցյալ (había temido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'había, habías, había... + temido',
        descripcionHy: 'había, habías, había... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'había temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habías temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'había temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habíamos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habíais temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habían temido' },
        ],
      },
      {
        id: 'temer_ind_ant',
        nombreEs: 'Pretérito anterior de indicativo',
        nombreHy: 'Սահմանական հարակատար անցյալ (hube temido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'hube, hubiste, hubo... + temido',
        descripcionHy: 'hube, hubiste, hubo... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hube temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubiste temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubo temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubimos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubisteis temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieron temido' },
        ],
      },
      {
        id: 'temer_ind_fut_perf',
        nombreEs: 'Futuro perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ապառնի (habré temido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'habré, habrás, habrá... + temido',
        descripcionHy: 'habré, habrás, habrá... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habré temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrás temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habrá temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habremos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habréis temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrán temido' },
        ],
      },
      {
        id: 'temer_ind_cond_perf',
        nombreEs: 'Condicional perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար պայմանական (habría temido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'habría, habrías... + temido',
        descripcionHy: 'habría, habrías... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habría temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrías temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habría temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habríamos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habríais temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrían temido' },
        ],
      },
      // SUBJUNTIVO
      {
        id: 'temer_sub_pres',
        nombreEs: 'Presente de subjuntivo',
        nombreHy: 'Ըղձական ներկա',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'tema, temas, tema, temamos, temáis, teman (vocal temática opuesta -a-).',
        descripcionHy: 'tema, temas... (2-րդ խոնարհման հակառակ թեմատիկ ձայնավոր -a-)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'tema' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temas' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'tema' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temáis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'teman' },
        ],
      },
      {
        id: 'temer_sub_imp_ra',
        nombreEs: 'Pretérito imperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական անկատար անցյալ (-ra շարք)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'temiera, temieras, temiera, temiéramos, temierais, temieran.',
        descripcionHy: 'temiera, temieras, temiera, temiéramos, temierais, temieran.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temiera' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temieras' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temiera' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temiéramos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temierais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temieran' },
        ],
      },
      {
        id: 'temer_sub_imp_se',
        nombreEs: 'Pretérito imperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական անկատար անցյալ (-se շարք)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'temiese, temieses, temiese, temiésemos, temieseis, temiesen.',
        descripcionHy: 'temiese, temieses, temiese, temiésemos, temieseis, temiesen.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temiese' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temieses' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temiese' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temiésemos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temieseis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temiesen' },
        ],
      },
      {
        id: 'temer_sub_fut',
        nombreEs: 'Futuro simple de subjuntivo',
        nombreHy: 'Ըղձական պարզ ապառնի',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'temiere, temieres, temiere, temiéremos, temiereis, temieren.',
        descripcionHy: 'temiere, temieres, temiere, temiéremos, temiereis, temieren.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'temiere' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'temieres' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'temiere' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'temiéremos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'temiereis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'temieren' },
        ],
      },
      {
        id: 'temer_sub_perf_comp',
        nombreEs: 'Pretérito perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ներկա (haya temido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'haya, hayas, haya... + temido',
        descripcionHy: 'haya, hayas, haya... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'haya temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hayas temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'haya temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hayamos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hayáis temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hayan temido' },
        ],
      },
      {
        id: 'temer_sub_plusc_ra',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiera temido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiera, hubieras... + temido',
        descripcionHy: 'hubiera, hubieras... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiera temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieras temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiera temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéramos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubierais temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieran temido' },
        ],
      },
      {
        id: 'temer_sub_plusc_se',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiese temido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiese, hubieses... + temido',
        descripcionHy: 'hubiese, hubieses... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiese temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieses temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiese temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiésemos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubieseis temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubiesen temido' },
        ],
      },
      {
        id: 'temer_sub_fut_perf',
        nombreEs: 'Futuro perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ապառնի (hubiere temido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiere, hubieres... + temido',
        descripcionHy: 'hubiere, hubieres... + temido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiere temido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieres temido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiere temido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéremos temido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubiereis temido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieren temido' },
        ],
      },
      // IMPERATIVO
      {
        id: 'temer_imperativo',
        nombreEs: 'Imperativo (afirmativo y negativo)',
        nombreHy: 'Հրամայական եղանակ',
        tiempoTipo: 'simple',
        modo: 'imperativo',
        descripcionEs: 'tú (teme), vosotros (temed). Negativo: no temas, no temáis.',
        descripcionHy: 'tú (teme), vosotros (temed)։ Ժխտական՝ no temas, no temáis։',
        formas: [
          { personaEs: 'tú (afirmativo)', personaHy: 'դու (հաստատական)', forma: 'teme' },
          { personaEs: 'usted (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'tema' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք (հաստատական)', forma: 'temamos' },
          { personaEs: 'vosotros / vosotras (afirmativo)', personaHy: 'դուք (հաստատական)', forma: 'temed' },
          { personaEs: 'ustedes (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'teman' },
          { personaEs: 'tú (negativo)', personaHy: 'դու (ժխտական)', forma: 'no temas' },
        ],
      },
    ],
  },

  partir: {
    verbo: 'partir',
    infinitivoEs: 'partir',
    infinitivoHy: 'մեկնել / բաժանել',
    tipoEs: 'Regular',
    tipoHy: 'Կանոնավոր',
    conjugacionEs: 'Tercera (-ir)',
    conjugacionHy: 'Երրորդ (-ir)',
    noPersonales: [
      { nombreEs: 'Infinitivo simple', nombreHy: 'Պարզ անորոշ ձև', forma: 'partir' },
      { nombreEs: 'Gerundio simple', nombreHy: 'Պարզ գերունդիո', forma: 'partiendo' },
      { nombreEs: 'Participio', nombreHy: 'Դերբայ (Participio)', forma: 'partido' },
      { nombreEs: 'Infinitivo compuesto', nombreHy: 'Բաղադրյալ անորոշ ձև', forma: 'haber partido' },
      { nombreEs: 'Gerundio compuesto', nombreHy: 'Բաղադրյալ գերունդիո', forma: 'habiendo partido' },
    ],
    tiempos: [
      {
        id: 'partir_ind_pres',
        nombreEs: 'Presente de indicativo',
        nombreHy: 'Սահմանական ներկա',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'parto, partes, parte, partimos, partís, parten.',
        descripcionHy: 'parto, partes, parte, partimos, partís, parten.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'parto' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partes' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'parte' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partimos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partís' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'parten' },
        ],
      },
      {
        id: 'partir_ind_imp',
        nombreEs: 'Pretérito imperfecto de indicativo',
        nombreHy: 'Սահմանական անկատար անցյալ (-ía)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'partía, partías, partía, partíamos, partíais, partían.',
        descripcionHy: 'partía, partías, partía, partíamos, partíais, partían.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partía' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partías' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partía' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partíamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partíais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partían' },
        ],
      },
      {
        id: 'partir_ind_perf_simple',
        nombreEs: 'Pretérito perfecto simple (indefinido)',
        nombreHy: 'Սահմանական ավարտված անցյալ (partí)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'partí, partiste, partió, partimos, partisteis, partieron.',
        descripcionHy: 'partí, partiste, partió, partimos, partisteis, partieron.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partí' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partiste' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partió' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partimos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partisteis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partieron' },
        ],
      },
      {
        id: 'partir_ind_fut',
        nombreEs: 'Futuro simple de indicativo',
        nombreHy: 'Սահմանական պարզ ապառնի',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'partiré, partirás, partirá, partiremos, partiréis, partirán.',
        descripcionHy: 'partiré, partirás, partirá, partiremos, partiréis, partirán.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partiré' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partirás' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partirá' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partiremos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partiréis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partirán' },
        ],
      },
      {
        id: 'partir_ind_cond',
        nombreEs: 'Condicional simple de indicativo',
        nombreHy: 'Սահմանական պարզ պայմանական',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'partiría, partirías, partiría, partiríamos, partiríais, partirían.',
        descripcionHy: 'partiría, partirías, partiría, partiríamos, partiríais, partirían.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partiría' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partirías' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partiría' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partiríamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partiríais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partirían' },
        ],
      },
      // COMPUESTOS INDICATIVO
      {
        id: 'partir_ind_perf_comp',
        nombreEs: 'Pretérito perfecto compuesto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ներկա (he partido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'he, has, ha... + partido',
        descripcionHy: 'he, has, ha... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'he partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'has partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'ha partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hemos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habéis partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'han partido' },
        ],
      },
      {
        id: 'partir_ind_plusc',
        nombreEs: 'Pretérito pluscuamperfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար անցյալ (había partido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'había, habías... + partido',
        descripcionHy: 'había, habías... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'había partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habías partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'había partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habíamos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habíais partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habían partido' },
        ],
      },
      {
        id: 'partir_ind_ant',
        nombreEs: 'Pretérito anterior de indicativo',
        nombreHy: 'Սահմանական հարակատար անցյալ (hube partido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'hube, hubiste, hubo... + partido',
        descripcionHy: 'hube, hubiste, hubo... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hube partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubiste partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubo partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubimos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubisteis partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieron partido' },
        ],
      },
      {
        id: 'partir_ind_fut_perf',
        nombreEs: 'Futuro perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ապառնի (habré partido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'habré, habrás... + partido',
        descripcionHy: 'habré, habrás... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habré partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrás partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habrá partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habremos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habréis partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrán partido' },
        ],
      },
      {
        id: 'partir_ind_cond_perf',
        nombreEs: 'Condicional perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար պայմանական (habría partido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'habría, habrías... + partido',
        descripcionHy: 'habría, habrías... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habría partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrías partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habría partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habríamos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habríais partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrían partido' },
        ],
      },
      // SUBJUNTIVO
      {
        id: 'partir_sub_pres',
        nombreEs: 'Presente de subjuntivo',
        nombreHy: 'Ըղձական ներկա',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'parta, partas, parta, partamos, partáis, partan.',
        descripcionHy: 'parta, partas, parta, partamos, partáis, partan.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'parta' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partas' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'parta' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partáis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partan' },
        ],
      },
      {
        id: 'partir_sub_imp_ra',
        nombreEs: 'Pretérito imperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական անկատար անցյալ (-ra շարք)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'partiera, partieras, partiera, partiéramos, partierais, partieran.',
        descripcionHy: 'partiera, partieras, partiera, partiéramos, partierais, partieran.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partiera' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partieras' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partiera' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partiéramos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partierais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partieran' },
        ],
      },
      {
        id: 'partir_sub_imp_se',
        nombreEs: 'Pretérito imperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական անկատար անցյալ (-se շարք)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'partiese, partieses, partiese, partiésemos, partieseis, partiesen.',
        descripcionHy: 'partiese, partieses, partiese, partiésemos, partieseis, partiesen.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partiese' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partieses' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partiese' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partiésemos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partieseis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partiesen' },
        ],
      },
      {
        id: 'partir_sub_fut',
        nombreEs: 'Futuro simple de subjuntivo',
        nombreHy: 'Ըղձական պարզ ապառնի',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'partiere, partieres, partiere, partiéremos, partiereis, partieren.',
        descripcionHy: 'partiere, partieres, partiere, partiéremos, partiereis, partieren.',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'partiere' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'partieres' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'partiere' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'partiéremos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'partiereis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'partieren' },
        ],
      },
      {
        id: 'partir_sub_perf_comp',
        nombreEs: 'Pretérito perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ներկա (haya partido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'haya, hayas... + partido',
        descripcionHy: 'haya, hayas... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'haya partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hayas partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'haya partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hayamos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hayáis partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hayan partido' },
        ],
      },
      {
        id: 'partir_sub_plusc_ra',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiera partido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiera, hubieras... + partido',
        descripcionHy: 'hubiera, hubieras... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiera partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieras partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiera partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéramos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubierais partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieran partido' },
        ],
      },
      {
        id: 'partir_sub_plusc_se',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiese partido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiese, hubieses... + partido',
        descripcionHy: 'hubiese, hubieses... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiese partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieses partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiese partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiésemos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubieseis partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubiesen partido' },
        ],
      },
      {
        id: 'partir_sub_fut_perf',
        nombreEs: 'Futuro perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ապառնի (hubiere partido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiere, hubieres... + partido',
        descripcionHy: 'hubiere, hubieres... + partido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiere partido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieres partido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiere partido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéremos partido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubiereis partido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieren partido' },
        ],
      },
      // IMPERATIVO
      {
        id: 'partir_imperativo',
        nombreEs: 'Imperativo (afirmativo y negativo)',
        nombreHy: 'Հրամայական եղանակ',
        tiempoTipo: 'simple',
        modo: 'imperativo',
        descripcionEs: 'tú (parte), vosotros (partid). Negativo: no partas, no partáis.',
        descripcionHy: 'tú (parte), vosotros (partid)։ Ժխտական՝ no partas, no partáis։',
        formas: [
          { personaEs: 'tú (afirmativo)', personaHy: 'դու (հաստատական)', forma: 'parte' },
          { personaEs: 'usted (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'parta' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք (հաստատական)', forma: 'partamos' },
          { personaEs: 'vosotros / vosotras (afirmativo)', personaHy: 'դուք (հաստատական)', forma: 'partid' },
          { personaEs: 'ustedes (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'partan' },
          { personaEs: 'tú (negativo)', personaHy: 'դու (ժխտական)', forma: 'no partas' },
        ],
      },
    ],
  },

  ser: {
    verbo: 'ser',
    infinitivoEs: 'ser',
    infinitivoHy: 'լինել',
    tipoEs: 'Irregular',
    tipoHy: 'Անկանոն',
    conjugacionEs: 'Irregular (-er)',
    conjugacionHy: 'Անկանոն (-er)',
    noPersonales: [
      { nombreEs: 'Infinitivo simple', nombreHy: 'Պարզ անորոշ ձև', forma: 'ser' },
      { nombreEs: 'Gerundio simple', nombreHy: 'Պարզ գերունդիո', forma: 'siendo' },
      { nombreEs: 'Participio', nombreHy: 'Դերբայ (Participio)', forma: 'sido' },
      { nombreEs: 'Infinitivo compuesto', nombreHy: 'Բաղադրյալ անորոշ ձև', forma: 'haber sido' },
      { nombreEs: 'Gerundio compuesto', nombreHy: 'Բաղադրյալ գերունդիո', forma: 'habiendo sido' },
    ],
    tiempos: [
      {
        id: 'ser_ind_pres',
        nombreEs: 'Presente de indicativo',
        nombreHy: 'Սահմանական ներկա (soy, eres...)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'Formas totalmente irregulares: soy, eres, es, somos, sois, son.',
        descripcionHy: 'Ամբողջությամբ անկանոն ձևեր՝ soy, eres, es, somos, sois, son։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'soy' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'eres' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'es' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'somos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'sois' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'son' },
        ],
      },
      {
        id: 'ser_ind_imp',
        nombreEs: 'Pretérito imperfecto de indicativo',
        nombreHy: 'Սահմանական անկատար անցյալ (era, eras...)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'era, eras, era, éramos, erais, eran.',
        descripcionHy: 'era, eras, era, éramos, erais, eran։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'era' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'eras' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'era' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'éramos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'erais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'eran' },
        ],
      },
      {
        id: 'ser_ind_perf_simple',
        nombreEs: 'Pretérito perfecto simple (indefinido)',
        nombreHy: 'Սահմանական ավարտված անցյալ (fui, fuiste...)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'fui, fuiste, fue, fuimos, fuisteis, fueron (idéntico al pasado de ir).',
        descripcionHy: 'fui, fuiste, fue, fuimos, fuisteis, fueron (նույնական է ir բայի հետ)։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'fui' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'fuiste' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'fue' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'fuimos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'fuisteis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'fueron' },
        ],
      },
      {
        id: 'ser_ind_fut',
        nombreEs: 'Futuro simple de indicativo',
        nombreHy: 'Սահմանական պարզ ապառնի (seré, serás...)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'seré, serás, será, seremos, seréis, serán.',
        descripcionHy: 'seré, serás, será, seremos, seréis, serán։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'seré' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'serás' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'será' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'seremos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'seréis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'serán' },
        ],
      },
      {
        id: 'ser_ind_cond',
        nombreEs: 'Condicional simple de indicativo',
        nombreHy: 'Սահմանական պարզ պայմանական (sería, serías...)',
        tiempoTipo: 'simple',
        modo: 'indicativo',
        descripcionEs: 'sería, serías, sería, seríamos, seríais, serían.',
        descripcionHy: 'sería, serías, sería, seríamos, seríais, serían։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'sería' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'serías' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'sería' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'seríamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'seríais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'serían' },
        ],
      },
      // COMPUESTOS INDICATIVO
      {
        id: 'ser_ind_perf_comp',
        nombreEs: 'Pretérito perfecto compuesto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ներկա (he sido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'he, has, ha... + sido',
        descripcionHy: 'he, has, ha... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'he sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'has sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'ha sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hemos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habéis sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'han sido' },
        ],
      },
      {
        id: 'ser_ind_plusc',
        nombreEs: 'Pretérito pluscuamperfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար անցյալ (había sido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'había, habías... + sido',
        descripcionHy: 'había, habías... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'había sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habías sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'había sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habíamos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habíais sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habían sido' },
        ],
      },
      {
        id: 'ser_ind_ant',
        nombreEs: 'Pretérito anterior de indicativo',
        nombreHy: 'Սահմանական հարակատար անցյալ (hube sido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'hube, hubiste... + sido',
        descripcionHy: 'hube, hubiste... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hube sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubiste sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubo sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubimos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubisteis sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieron sido' },
        ],
      },
      {
        id: 'ser_ind_fut_perf',
        nombreEs: 'Futuro perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար ապառնի (habré sido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'habré, habrás... + sido',
        descripcionHy: 'habré, habrás... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habré sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrás sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habrá sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habremos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habréis sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrán sido' },
        ],
      },
      {
        id: 'ser_ind_cond_perf',
        nombreEs: 'Condicional perfecto de indicativo',
        nombreHy: 'Սահմանական վաղակատար պայմանական (habría sido)',
        tiempoTipo: 'compuesto',
        modo: 'indicativo',
        descripcionEs: 'habría, habrías... + sido',
        descripcionHy: 'habría, habrías... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'habría sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'habrías sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'habría sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'habríamos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'habríais sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'habrían sido' },
        ],
      },
      // SUBJUNTIVO
      {
        id: 'ser_sub_pres',
        nombreEs: 'Presente de subjuntivo',
        nombreHy: 'Ըղձական ներկա (sea, seas...)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'sea, seas, sea, seamos, seáis, sean.',
        descripcionHy: 'sea, seas, sea, seamos, seáis, sean։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'sea' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'seas' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'sea' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'seamos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'seáis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'sean' },
        ],
      },
      {
        id: 'ser_sub_imp_ra',
        nombreEs: 'Pretérito imperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական անկատար անցյալ (fuera, fueras...)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'fuera, fueras, fuera, fuéramos, fuerais, fueran.',
        descripcionHy: 'fuera, fueras, fuera, fuéramos, fuerais, fueran։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'fuera' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'fueras' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'fuera' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'fuéramos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'fuerais' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'fueran' },
        ],
      },
      {
        id: 'ser_sub_imp_se',
        nombreEs: 'Pretérito imperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական անկատար անցյալ (fuese, fueses...)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'fuese, fueses, fuese, fuésemos, fueseis, fuesen.',
        descripcionHy: 'fuese, fueses, fuese, fuésemos, fueseis, fuesen։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'fuese' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'fueses' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'fuese' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'fuésemos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'fueseis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'fuesen' },
        ],
      },
      {
        id: 'ser_sub_fut',
        nombreEs: 'Futuro simple de subjuntivo',
        nombreHy: 'Ըղձական պարզ ապառնի (fuere, fueres...)',
        tiempoTipo: 'simple',
        modo: 'subjuntivo',
        descripcionEs: 'fuere, fueres, fuere, fuéremos, fuereis, fueren.',
        descripcionHy: 'fuere, fueres, fuere, fuéremos, fuereis, fueren։',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'fuere' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'fueres' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'fuere' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'fuéremos' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'fuereis' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'fueren' },
        ],
      },
      {
        id: 'ser_sub_perf_comp',
        nombreEs: 'Pretérito perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ներկա (haya sido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'haya, hayas... + sido',
        descripcionHy: 'haya, hayas... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'haya sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hayas sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'haya sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hayamos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hayáis sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hayan sido' },
        ],
      },
      {
        id: 'ser_sub_plusc_ra',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-ra)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiera sido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiera, hubieras... + sido',
        descripcionHy: 'hubiera, hubieras... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiera sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieras sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiera sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéramos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubierais sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieran sido' },
        ],
      },
      {
        id: 'ser_sub_plusc_se',
        nombreEs: 'Pretérito pluscuamperfecto de subjuntivo (-se)',
        nombreHy: 'Ըղձական վաղակատար անցյալ (hubiese sido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiese, hubieses... + sido',
        descripcionHy: 'hubiese, hubieses... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiese sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieses sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiese sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiésemos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubieseis sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubiesen sido' },
        ],
      },
      {
        id: 'ser_sub_fut_perf',
        nombreEs: 'Futuro perfecto de subjuntivo',
        nombreHy: 'Ըղձական վաղակատար ապառնի (hubiere sido)',
        tiempoTipo: 'compuesto',
        modo: 'subjuntivo',
        descripcionEs: 'hubiere, hubieres... + sido',
        descripcionHy: 'hubiere, hubieres... + sido',
        formas: [
          { personaEs: 'yo', personaHy: 'ես', forma: 'hubiere sido' },
          { personaEs: 'tú', personaHy: 'դու', forma: 'hubieres sido' },
          { personaEs: 'él / ella / usted', personaHy: 'նա / Դուք', forma: 'hubiere sido' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք', forma: 'hubiéremos sido' },
          { personaEs: 'vosotros / vosotras', personaHy: 'դուք', forma: 'hubiereis sido' },
          { personaEs: 'ellos / ellas / ustedes', personaHy: 'նրանք / Դուք', forma: 'hubieren sido' },
        ],
      },
      // IMPERATIVO
      {
        id: 'ser_imperativo',
        nombreEs: 'Imperativo (afirmativo y negativo)',
        nombreHy: 'Հրամայական եղանակ (sé / sed)',
        tiempoTipo: 'simple',
        modo: 'imperativo',
        descripcionEs: 'tú (sé con tilde), vosotros (sed). Negativo: no seas, no seáis.',
        descripcionHy: 'tú (sé շեշտով), vosotros (sed)։ Ժխտական՝ no seas, no seáis։',
        formas: [
          { personaEs: 'tú (afirmativo)', personaHy: 'դու (հաստատական)', forma: 'sé' },
          { personaEs: 'usted (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'sea' },
          { personaEs: 'nosotros / nosotras', personaHy: 'մենք (հաստատական)', forma: 'seamos' },
          { personaEs: 'vosotros / vosotras (afirmativo)', personaHy: 'դուք (հաստատական)', forma: 'sed' },
          { personaEs: 'ustedes (afirmativo)', personaHy: 'Դուք (հաստատական)', forma: 'sean' },
          { personaEs: 'tú (negativo)', personaHy: 'դու (ժխտական)', forma: 'no seas' },
        ],
      },
    ],
  },
};
