/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Question } from './types';

export const QUESTIONS_PART_2: Question[] = [
  // 6. Distinguir formas simples, compuestas y no personales (10 preguntas)
  {
    id: 'dist_1',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Qué tipo de forma verbal es "partiendo"?',
    enunciadoHy: 'Ի՞նչ տեսակի բայաձև է «partiendo»-ն։',
    opciones: [
      'Forma no personal (gerundio simple)',
      'Forma personal simple',
      'Forma personal compuesta',
      'Forma no personal compuesta'
    ],
    respuestaCorrecta: 'Forma no personal (gerundio simple)',
    explicacionEs: '"Partiendo" es un gerundio simple; no expresa por sí mismo persona ni número.',
    explicacionHy: '«Partiendo»-ն պարզ գերունդիո է․ ինքնուրույն չի արտահայտում դեմք և թիվ։',
  },
  {
    id: 'dist_2',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Qué tipo de forma verbal es "habíamos temido"?',
    enunciadoHy: 'Ի՞նչ տեսակի բայաձև է «habíamos temido»-ն։',
    opciones: [
      'Forma personal compuesta',
      'Forma personal simple',
      'Forma no personal compuesta',
      'Forma no personal simple'
    ],
    respuestaCorrecta: 'Forma personal compuesta',
    explicacionEs: 'Consta del auxiliar conjugado en 1.ª plural + participio: es forma personal compuesta.',
    explicacionHy: 'Կազմված է խոնարհված haber-ից և participio-ից՝ դիմավոր բաղադրյալ ձև է։',
  },
  {
    id: 'dist_3',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Qué tipo de forma verbal es "amaría"?',
    enunciadoHy: 'Ի՞նչ տեսակի բայաձև է «amaría»-ն։',
    opciones: [
      'Forma personal simple',
      'Forma personal compuesta',
      'Forma no personal simple',
      'Forma no personal compuesta'
    ],
    respuestaCorrecta: 'Forma personal simple',
    explicacionEs: 'Consta de un solo verbo con desinencias personales: es forma personal simple.',
    explicacionHy: 'Մեկ բառից կազմված դիմավոր ձև է՝ պարզ դիմավոր ձև։',
  },
  {
    id: 'dist_4',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Qué tipo de forma verbal es "haber sido"?',
    enunciadoHy: 'Ի՞նչ տեսակի բայաձև է «haber sido»-ն։',
    opciones: [
      'Forma no personal compuesta (infinitivo compuesto)',
      'Forma personal compuesta',
      'Forma no personal simple',
      'Forma personal simple'
    ],
    respuestaCorrecta: 'Forma no personal compuesta (infinitivo compuesto)',
    explicacionEs: 'Es un infinitivo compuesto (haber + participio sido), por tanto no personal compuesta.',
    explicacionHy: 'Բաղադրյալ անորոշ ձև է (haber + participio sido)՝ անդեմ բաղադրյալ ձև։',
  },
  {
    id: 'dist_5',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Cuál de las siguientes formas es NO PERSONAL simple?',
    enunciadoHy: 'Հետևյալ ձևերից ո՞րն է ՊԱՐԶ ԱՆԴԵՄ ձև։',
    opciones: ['amado', 'he amado', 'amaba', 'habiendo amado'],
    respuestaCorrecta: 'amado',
    explicacionEs: '"Amado" es el participio simple.',
    explicacionHy: '«Amado»-ն պարզ դերբայ (participio) է։',
  },
  {
    id: 'dist_6',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Cuál de las siguientes formas es una forma COMPUESTA de subjuntivo?',
    enunciadoHy: 'Հետևյալներից ո՞րն է ըղձական եղանակի ԲԱՂԱԴՐՅԱԼ ձև։',
    opciones: ['hubiera amado', 'había amado', 'amara', 'habría amado'],
    respuestaCorrecta: 'hubiera amado',
    explicacionEs: '"Hubiera amado" es pretérito pluscuamperfecto de subjuntivo.',
    explicacionHy: '«Hubiera amado»-ն ըղձական եղանակի վաղակատար անցյալն է։',
  },
  {
    id: 'dist_7',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Qué distingue una forma personal de una no personal?',
    enunciadoHy: 'Ինչո՞վ է դիմավոր ձևը տարբերվում անդեմ ձևից։',
    opciones: [
      'La forma personal indica persona y número; la no personal no los indica',
      'La forma personal siempre lleva dos palabras y la no personal una',
      'La forma personal solo existe en presente',
      'No hay ninguna diferencia morfológica'
    ],
    respuestaCorrecta: 'La forma personal indica persona y número; la no personal no los indica',
    explicacionEs: 'Las formas no personales carecen de desinencias de persona y número.',
    explicacionHy: 'Անդեմ ձևերը չունեն դեմքի և թվի քերականական վերջավորություններ։',
  },
  {
    id: 'dist_8',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Qué es "habiendo temido"?',
    enunciadoHy: 'Ի՞նչ է «habiendo temido»-ն։',
    opciones: [
      'Gerundio compuesto (forma no personal)',
      'Pretérito perfecto de subjuntivo',
      'Gerundio simple',
      'Participio compuesto'
    ],
    respuestaCorrecta: 'Gerundio compuesto (forma no personal)',
    explicacionEs: 'Estructura de gerundio compuesto: habiendo + temido.',
    explicacionHy: 'Բաղադրյալ գերունդիոյի կառուցվածք՝ habiendo + temido։',
  },
  {
    id: 'dist_9',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Es "temed" una forma personal?',
    enunciadoHy: 'Արդյո՞ք «temed»-ը դիմավոր ձև է։',
    opciones: [
      'Sí, es imperativo de 2.ª persona del plural (vosotros)',
      'No, es un participio antiguo',
      'No, es una forma no personal',
      'Sí, pero solo para singular'
    ],
    respuestaCorrecta: 'Sí, es imperativo de 2.ª persona del plural (vosotros)',
    explicacionEs: 'El imperativo "temed" se dirige específicamente a la 2.ª persona del plural.',
    explicacionHy: '«Temed» հրամայականը հասցեագրված է հոգնակի 2-րդ դեմքին (vosotros)։',
  },
  {
    id: 'dist_10',
    categoria: 'distinguir',
    categoriaEs: '6. Distinguir tipos de forma',
    categoriaHy: '6. Տարբերակել ձևերի տեսակները',
    enunciadoEs: '¿Cuál de las siguientes formas es simple de indicativo?',
    enunciadoHy: 'Հետևյալներից ո՞րն է սահմանական եղանակի պարզ ձև։',
    opciones: ['temeré', 'he temido', 'habiendo temido', 'haya temido'],
    respuestaCorrecta: 'temeré',
    explicacionEs: '"Temeré" es el futuro simple de indicativo.',
    explicacionHy: '«Temeré»-ն սահմանական պարզ ապառնին է։',
  },

  // 7. Analizar un verbo (10 preguntas)
  {
    id: 'an_1',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza completamente la forma "habíamos partido".',
    enunciadoHy: 'Ամբողջությամբ վերլուծի՛ր «habíamos partido» բայաձևը։',
    opciones: [
      '1.ª plural del pretérito pluscuamperfecto de indicativo de partir (3.ª conj., compuesta)',
      '1.ª plural del condicional perfecto de indicativo de partir',
      '2.ª plural del pretérito anterior de partir',
      '1.ª plural del pretérito imperfecto de partir'
    ],
    respuestaCorrecta: '1.ª plural del pretérito pluscuamperfecto de indicativo de partir (3.ª conj., compuesta)',
    explicacionEs: 'Infinitivo: partir (3.ª) | 1.ª plural | Pretérito pluscuamperfecto indicativo | Forma compuesta.',
    explicacionHy: 'Անորոշ՝ partir (3-րդ) | Հոգնակի 1-ին դեմք | Սահմանական pluscuamperfecto | Բաղադրյալ ձև։',
  },
  {
    id: 'an_2',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza la forma "temieseis".',
    enunciadoHy: 'Վերլուծի՛ր «temieseis» բայաձևը։',
    opciones: [
      '2.ª plural del pretérito imperfecto de subjuntivo de temer (2.ª conj., simple)',
      '2.ª plural del condicional simple de temer',
      '2.ª plural del pretérito perfecto simple de temer',
      '2.ª plural del futuro simple de subjuntivo de temer'
    ],
    respuestaCorrecta: '2.ª plural del pretérito imperfecto de subjuntivo de temer (2.ª conj., simple)',
    explicacionEs: 'Infinitivo: temer (2.ª) | 2.ª plural | Pretérito imperfecto de subjuntivo (-se) | Forma simple.',
    explicacionHy: 'Անորոշ՝ temer (2-րդ) | Հոգնակի 2-րդ դեմք | Ըղձական imperfecto (-se) | Պարզ ձև։',
  },
  {
    id: 'an_3',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "seremos".',
    enunciadoHy: 'Վերլուծի՛ր «seremos» բայաձևը։',
    opciones: [
      '1.ª plural del futuro simple de indicativo del verbo ser (irregular, simple)',
      '1.ª plural del presente de indicativo de ser',
      '1.ª plural del condicional simple de ser',
      '1.ª plural del presente de subjuntivo de ser'
    ],
    respuestaCorrecta: '1.ª plural del futuro simple de indicativo del verbo ser (irregular, simple)',
    explicacionEs: 'Infinitivo: ser (irregular) | 1.ª plural | Futuro simple de indicativo | Forma simple.',
    explicacionHy: 'Անորոշ՝ ser (անկանոն) | Հոգնակի 1-ին դեմք | Սահմանական պարզ ապառնի | Պարզ ձև։',
  },
  {
    id: 'an_4',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "amó".',
    enunciadoHy: 'Վերլուծի՛ր «amó» բայաձևը։',
    opciones: [
      '3.ª singular del pretérito perfecto simple de indicativo de amar (1.ª conj., simple)',
      '1.ª singular del presente de indicativo de amar',
      '3.ª singular del presente de subjuntivo de amar',
      '2.ª singular del imperativo de amar'
    ],
    respuestaCorrecta: '3.ª singular del pretérito perfecto simple de indicativo de amar (1.ª conj., simple)',
    explicacionEs: '"Amó" con tilde en la -ó es 3.ª singular del pretérito perfecto simple de indicativo.',
    explicacionHy: '«Amó»-ն -ó-ի վրա շեշտով ավարտված անցյալի եզակի 3-րդ դեմքն է։',
  },
  {
    id: 'an_5',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "hube partido".',
    enunciadoHy: 'Վերլուծի՛ր «hube partido» բայաձևը։',
    opciones: [
      '1.ª singular del pretérito anterior de indicativo de partir (3.ª conj., compuesta)',
      '1.ª singular del pretérito pluscuamperfecto de indicativo',
      '1.ª singular del pretérito perfecto compuesto',
      '1.ª singular del condicional perfecto'
    ],
    respuestaCorrecta: '1.ª singular del pretérito anterior de indicativo de partir (3.ª conj., compuesta)',
    explicacionEs: 'Hube + participio = pretérito anterior de indicativo, 1.ª persona del singular.',
    explicacionHy: 'Hube + participio = սահմանական եղանակի pretérito anterior, եզակի 1-ին դեմք։',
  },
  {
    id: 'an_6',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "partiríais".',
    enunciadoHy: 'Վերլուծի՛ր «partiríais» բայաձևը։',
    opciones: [
      '2.ª plural del condicional simple de indicativo de partir (3.ª conj., simple)',
      '2.ª plural del futuro simple de indicativo de partir',
      '2.ª plural del pretérito imperfecto de subjuntivo',
      '2.ª plural del presente de indicativo de partir'
    ],
    respuestaCorrecta: '2.ª plural del condicional simple de indicativo de partir (3.ª conj., simple)',
    explicacionEs: 'Infinitivo partir + -íais = condicional simple, 2.ª persona plural (vosotros).',
    explicacionHy: 'Անորոշ partir + -íais = պարզ պայմանական, հոգնակի 2-րդ դեմք (vosotros)։',
  },
  {
    id: 'an_7',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "hayan sido".',
    enunciadoHy: 'Վերլուծի՛ր «hayan sido» բայաձևը։',
    opciones: [
      '3.ª plural del pretérito perfecto de subjuntivo del verbo ser (compuesta)',
      '3.ª plural del pretérito pluscuamperfecto de subjuntivo de ser',
      '3.ª plural del futuro perfecto de subjuntivo de ser',
      '3.ª plural del pretérito perfecto compuesto de indicativo de ser'
    ],
    respuestaCorrecta: '3.ª plural del pretérito perfecto de subjuntivo del verbo ser (compuesta)',
    explicacionEs: 'Auxiliar hayan (presente subjuntivo) + sido = pretérito perfecto de subjuntivo, 3.ª plural.',
    explicacionHy: 'Hayan + sido = ըղձական եղանակի pretérito perfecto, հոգնակի 3-րդ դեմք։',
  },
  {
    id: 'an_8',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "amabais".',
    enunciadoHy: 'Վերլուծի՛ր «amabais» բայաձևը։',
    opciones: [
      '2.ª plural del pretérito imperfecto de indicativo de amar (1.ª conj., simple)',
      '2.ª plural del condicional simple de indicativo de amar',
      '2.ª plural del presente de indicativo de amar',
      '2.ª plural del pretérito perfecto simple de amar'
    ],
    respuestaCorrecta: '2.ª plural del pretérito imperfecto de indicativo de amar (1.ª conj., simple)',
    explicacionEs: 'am- (lex) + -a- (vt) + -ba- (tiempo) + -is (desinencia vosotros) = pretérito imperfecto indicativo.',
    explicacionHy: 'am- + -a- + -ba- + -is = սահմանական անկատար անցյալ, հոգնակի 2-րդ դեմք։',
  },
  {
    id: 'an_9',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "sea".',
    enunciadoHy: 'Վերլուծի՛ր «sea» բայաձևը։',
    opciones: [
      '1.ª o 3.ª singular del presente de subjuntivo del verbo ser (irregular, simple)',
      '2.ª singular del imperativo afirmativo de ser',
      '1.ª singular del presente de indicativo de ser',
      '3.ª singular del pretérito imperfecto de ser'
    ],
    respuestaCorrecta: '1.ª o 3.ª singular del presente de subjuntivo del verbo ser (irregular, simple)',
    explicacionEs: '"Sea" corresponde a yo sea o él/ella/usted sea en presente de subjuntivo.',
    explicacionHy: '«Sea»-ն ըղձական ներկայի եզակի 1-ին կամ 3-րդ դեմքն է։',
  },
  {
    id: 'an_10',
    categoria: 'analizar',
    categoriaEs: '7. Analizar verbo',
    categoriaHy: '7. Վերլուծել բայը',
    enunciadoEs: 'Analiza "temiereis".',
    enunciadoHy: 'Վերլուծի՛ր «temiereis» բայաձևը։',
    opciones: [
      '2.ª plural del futuro simple de subjuntivo de temer (2.ª conj., simple)',
      '2.ª plural del condicional simple de temer',
      '2.ª plural del futuro simple de indicativo de temer',
      '2.ª plural del pretérito imperfecto de subjuntivo de temer'
    ],
    respuestaCorrecta: '2.ª plural del futuro simple de subjuntivo de temer (2.ª conj., simple)',
    explicacionEs: 'Terminación -re-is sobre el tema de pretérito: futuro simple de subjuntivo, 2.ª plural.',
    explicacionHy: '«Temiereis»-ը temer բայի ըղձական պարզ ապառնիի հոգնակի 2-րդ դեմքն է։',
  },

  // 8. Corregir errores (10 preguntas)
  {
    id: 'corr_1',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Encuentra el error: "Ellas han partidas esta mañana temprano".',
    enunciadoHy: 'Գտի՛ր սխալը․ «Ellas han partidas esta mañana temprano»։',
    opciones: [
      'Debe ser "han partido", porque el participio con haber es invariable',
      'Debe ser "han partiendo"',
      'Debe ser "habían partidas"',
      'No hay ningún error'
    ],
    respuestaCorrecta: 'Debe ser "han partido", porque el participio con haber es invariable',
    explicacionEs: 'El participio en los tiempos compuestos con haber nunca concuerda en género ni número.',
    explicacionHy: 'Haber-ի հետ բաղադրյալ ժամանակներում participio-ն երբեք չի փոխվում (միշտ -o)։',
  },
  {
    id: 'corr_2',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Encuentra el error: "Usted partes hacia el colegio a las ocho".',
    enunciadoHy: 'Գտի՛ր սխալը․ «Usted partes hacia el colegio a las ocho»։',
    opciones: [
      'Debe ser "Usted parte", porque usted exige verbo en 3.ª persona',
      'Debe ser "Usted partís"',
      'Debe ser "Usted partió"',
      'No hay error gramatical'
    ],
    respuestaCorrecta: 'Debe ser "Usted parte", porque usted exige verbo en 3.ª persona',
    explicacionEs: '"Usted" lleva siempre el verbo en tercera persona del singular: "Usted parte".',
    explicacionHy: '«Usted» դերանվան հետ բայը միշտ դրվում է եզակի 3-րդ դեմքով՝ «Usted parte»։',
  },
  {
    id: 'corr_3',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Encuentra el error de tilde: "Mañana yo amare a mis amigos en el viaje".',
    enunciadoHy: 'Գտի՛ր շեշտի սխալը․ «Mañana yo amare a mis amigos en el viaje»։',
    opciones: [
      'Falta la tilde: debe ser "amaré" (futuro de indicativo)',
      'Debe escribirse "amáre"',
      'Debe ser "amó"',
      'Está correcto sin tilde'
    ],
    respuestaCorrecta: 'Falta la tilde: debe ser "amaré" (futuro de indicativo)',
    explicacionEs: 'El futuro simple de indicativo de 1.ª persona lleva tilde obligatoria: "yo amaré".',
    explicacionHy: 'Սահմանական ապառնիի 1-ին դեմքը պարտադիր շեշտվում է՝ «yo amaré»։',
  },
  {
    id: 'corr_4',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Corrige la afirmación: "El verbo SER es un verbo regular de la 2.ª conjugación".',
    enunciadoHy: 'Ուղղի՛ր պնդումը․ «SER բայը 2-րդ խոնարհման կանոնավոր բայ է»։',
    opciones: [
      'Falso: SER es un verbo completamente IRREGULAR',
      'Verdadero: SER sigue el modelo de temer',
      'Falso: SER es de la 1.ª conjugación',
      'Falso: SER no es un verbo'
    ],
    respuestaCorrecta: 'Falso: SER es un verbo completamente IRREGULAR',
    explicacionEs: 'SER es totalmente irregular (soy, era, fui, sea). Amar, temer y partir son regulares.',
    explicacionHy: 'SER-ն ամբողջությամբ անկանոն է (soy, era, fui, sea)։ Amar, temer և partir բայերն են կանոնավոր։',
  },
  {
    id: 'corr_5',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Corrige el imperativo para vosotros: "¡Chicos, no partir todavía!".',
    enunciadoHy: 'Ուղղի՛ր vosotros-ի ժխտական հրամայականը․ «¡Chicos, no partir todavía!»։',
    opciones: [
      'Debe ser "no partáis", porque el imperativo negativo usa el subjuntivo',
      'Debe ser "no partid"',
      'Debe ser "no parten"',
      'El infinitivo es la forma culta correcta'
    ],
    respuestaCorrecta: 'Debe ser "no partáis", porque el imperativo negativo usa el subjuntivo',
    explicacionEs: 'El imperativo negativo se forma siempre con el presente de subjuntivo: "no partáis".',
    explicacionHy: 'Ժխտական հրամայականը կազմվում է ըղձական ներկայով՝ «no partáis»։',
  },
  {
    id: 'corr_6',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Corrige el mandato afirmativo de vosotros: "¡Amigos, *amar a vuestros hermanos!".',
    enunciadoHy: 'Ուղղի՛ր vosotros-ի հաստատական հրամայականը․ «¡Amigos, *amar a vuestros hermanos!»։',
    opciones: [
      'Debe ser "amad", sustituyendo la -r del infinitivo por -d',
      'Debe ser "amen"',
      'Debe ser "amáis"',
      'Debe ser "améis"'
    ],
    respuestaCorrecta: 'Debe ser "amad", sustituyendo la -r del infinitivo por -d',
    explicacionEs: 'El imperativo afirmativo normativo de vosotros termina en -d: "amad", no el infinitivo.',
    explicacionHy: 'Vosotros-ի նորմատիվ հաստատական հրամայականը վերջանում է -d-ով՝ «amad»։',
  },
  {
    id: 'corr_7',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Corrige la confusión: "¿Había partido y habría partido son el mismo tiempo?".',
    enunciadoHy: 'Ուղղի՛ր շփոթմունքը․ «Había partido և habría partido նույն ժամանակաձևե՞րն են»։',
    opciones: [
      'No: había partido es pluscuamperfecto; habría partido es condicional perfecto',
      'Sí, son variantes de la misma forma',
      'No: había partido es subjuntivo y habría partido es indicativo',
      'No: ambos son tiempos simples'
    ],
    respuestaCorrecta: 'No: había partido es pluscuamperfecto; habría partido es condicional perfecto',
    explicacionEs: '"Había" es imperfecto (pluscuamperfecto); "habría" con -r- es condicional perfecto.',
    explicacionHy: '«Había»-ն անկատար է (վաղակատար անցյալ), «habría»-ն՝ պայմանական (վաղակատար պայմանական)։',
  },
  {
    id: 'corr_8',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Encuentra el error: "Si él *habría estudiado, habría aprobado".',
    enunciadoHy: 'Գտի՛ր սխալը․ «Si él *habría estudiado, habría aprobado»։',
    opciones: [
      'En la condición con "si" se usa subjuntivo: "hubiera estudiado" o "hubiese estudiado"',
      'Debe usarse presente: "estudia"',
      'Debe usarse futuro: "habrá estudiado"',
      'La frase es completamente correcta'
    ],
    respuestaCorrecta: 'En la condición con "si" se usa subjuntivo: "hubiera estudiado" o "hubiese estudiado"',
    explicacionEs: 'En la prótasis condicional con "si" es incorrecto el condicional; se exige pluscuamperfecto de subjuntivo.',
    explicacionHy: '«Si»-ով պայմանական նախադասության մեջ պահանջվում է ըղձական վաղակատար անցյալ (hubiera/hubiese)։',
  },
  {
    id: 'corr_9',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Corrige la tilde: "El profesor me dijo: *se amable con los nuevos".',
    enunciadoHy: 'Ուղղի՛ր շեշտի սխալը․ «El profesor me dijo: *se amable con los nuevos»։',
    opciones: [
      'Debe llevar tilde: "sé amable", porque es el imperativo de ser',
      'Debe escribirse "sea amable"',
      'No lleva tilde nunca',
      'Debe ser "sois amable"'
    ],
    respuestaCorrecta: 'Debe llevar tilde: "sé amable", porque es el imperativo de ser',
    explicacionEs: 'El imperativo "sé" lleva tilde diacrítica obligatoria para distinguirse del pronombre reflexivo "se".',
    explicacionHy: 'Հրամայական «sé»-ն կրում է տարբերակիչ շեշտ (sé amable)՝ «se» դերանունից զատվելու համար։',
  },
  {
    id: 'corr_10',
    categoria: 'corregir',
    categoriaEs: '8. Corregir errores',
    categoriaHy: '8. Ուղղել սխալները',
    enunciadoEs: 'Corrige la afirmación: "Amara y amase son dos tiempos verbales diferentes".',
    enunciadoHy: 'Ուղղի՛ր պնդումը․ «Amara և amase երկու տարբեր ժամանակաձևեր են»։',
    opciones: [
      'Falso: son dos series del mismo tiempo (pretérito imperfecto de subjuntivo)',
      'Verdadero: amara es pasado y amase es futuro',
      'Verdadero: amara es indicativo y amase es subjuntivo',
      'Falso: amara es condicional'
    ],
    respuestaCorrecta: 'Falso: son dos series del mismo tiempo (pretérito imperfecto de subjuntivo)',
    explicacionEs: 'Amara y amase son dos variantes morfológicas idénticas en valor del pretérito imperfecto de subjuntivo.',
    explicacionHy: 'Amara-ն և amase-ն նույն ըղձական անկատար անցյալի երկու համարժեք շարքերն են։',
  },

  // 9. Transformar una forma siguiendo una instrucción explícita (10 preguntas)
  {
    id: 'tr_1',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: nosotros, partir, pretérito pluscuamperfecto de indicativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ մենք (nosotros), partir, սահմանական վաղակատար անցյալ (pluscuamperfecto)։',
    opciones: ['habíamos partido', 'habríamos partido', 'hube partido', 'hubiéramos partido'],
    respuestaCorrecta: 'habíamos partido',
    explicacionEs: '1.ª persona del plural de haber en imperfecto ("habíamos") + participio ("partido").',
    explicacionHy: 'Haber-ի անկատար անցյալի հոգնակի 1-ին դեմքը («habíamos») + «partido»։',
  },
  {
    id: 'tr_2',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: tú, temer, condicional simple de indicativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ դու (tú), temer, սահմանական պարզ պայմանական (condicional simple)։',
    opciones: ['temerías', 'temías', 'temieras', 'temerás'],
    respuestaCorrecta: 'temerías',
    explicacionEs: 'Infinitivo temer + desinencia -ías = "temerías".',
    explicacionHy: 'Անորոշ temer + -ías վերջավորություն = «temerías»։',
  },
  {
    id: 'tr_3',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: vosotros, amar, pretérito perfecto simple de indicativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ դուք (vosotros), amar, սահմանական ավարտված անցյալ (indefinido)։',
    opciones: ['amasteis', 'amabais', 'amarais', 'amaríais'],
    respuestaCorrecta: 'amasteis',
    explicacionEs: 'En el pretérito perfecto simple para vosotros corresponde "amasteis".',
    explicacionHy: 'Ավարտված անցյալում vosotros-ի համար համապատասխանում է «amasteis»-ը։',
  },
  {
    id: 'tr_4',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: ellos, ser, pretérito imperfecto de subjuntivo (serie -ra).',
    enunciadoHy: 'Փոխակերպի՛ր՝ նրանք (ellos), ser, ըղձական անկատար անցյալ (-ra շարք)։',
    opciones: ['fueran', 'fuesen', 'eran', 'serían'],
    respuestaCorrecta: 'fueran',
    respuestasAlternativasValidas: ['fuesen'],
    explicacionEs: 'Para ellos en imperfecto de subjuntivo serie -ra corresponde "fueran" (o "fuesen" en serie -se).',
    explicacionHy: 'Ellos դեմքի համար -ra շարքով համապատասխանում է «fueran»-ը (կամ «fuesen» -se շարքով)։',
  },
  {
    id: 'tr_5',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: yo, partir, futuro simple de indicativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ ես (yo), partir, սահմանական պարզ ապառնի (futuro simple)։',
    opciones: ['partiré', 'partire', 'partiría', 'partí'],
    respuestaCorrecta: 'partiré',
    explicacionEs: '1.ª persona singular con tilde en la -é: "partiré".',
    explicacionHy: 'Եզակի 1-ին դեմքը -é-ի վրա շեշտով՝ «partiré»։',
  },
  {
    id: 'tr_6',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: usted, amar, presente de subjuntivo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ Դուք (usted), amar, ըղձական ներկա (presente de subjuntivo)։',
    opciones: ['ame', 'ama', 'ames', 'amé'],
    respuestaCorrecta: 'ame',
    explicacionEs: 'Usted utiliza la 3.ª persona singular: "ame".',
    explicacionHy: 'Usted-ն օգտագործում է եզակի 3-րդ դեմքը՝ «ame»։',
  },
  {
    id: 'tr_7',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: vosotros, ser, imperativo afirmativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ դուք (vosotros), ser, հաստատական հրամայական (imperativo)։',
    opciones: ['sed', 'sé', 'sois', 'seáis'],
    respuestaCorrecta: 'sed',
    explicacionEs: 'El imperativo afirmativo de vosotros para ser es "sed".',
    explicacionHy: 'Ser-ի vosotros դեմքի հաստատական հրամայականն է «sed»։',
  },
  {
    id: 'tr_8',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: él, temer, pretérito anterior de indicativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ նա (él), temer, սահմանական հարակատար անցյալ (pretérito anterior)։',
    opciones: ['hubo temido', 'había temido', 'ha temido', 'habrá temido'],
    respuestaCorrecta: 'hubo temido',
    explicacionEs: '3.ª persona singular de pretérito perfecto simple de haber ("hubo") + "temido".',
    explicacionHy: 'Haber-ի ավարտված անցյալի 3-րդ դեմք («hubo») + «temido»։',
  },
  {
    id: 'tr_9',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: nosotros, ser, pretérito imperfecto de indicativo.',
    enunciadoHy: 'Փոխակերպի՛ր՝ մենք (nosotros), ser, սահմանական անկատար անցյալ (pretérito imperfecto)։',
    opciones: ['éramos', 'fuimos', 'seríamos', 'ésemos'],
    respuestaCorrecta: 'éramos',
    explicacionEs: 'La forma es "éramos", con tilde en la vocal esdrújula.',
    explicacionHy: 'Ձևն է «éramos»՝ նախավերջին վանկի շեշտադրությամբ։',
  },
  {
    id: 'tr_10',
    categoria: 'transformar',
    categoriaEs: '9. Transformar forma',
    categoriaHy: '9. Փոխակերպել բայաձևը',
    enunciadoEs: 'Transforma: tú, partir, pretérito perfecto simple (indefinido).',
    enunciadoHy: 'Փոխակերպի՛ր՝ դու (tú), partir, սահմանական ավարտված անցյալ (indefinido)։',
    opciones: ['partiste', 'partías', 'partirás', 'partieras'],
    respuestaCorrecta: 'partiste',
    explicacionEs: 'La 2.ª persona del singular del pretérito perfecto simple es "partiste" (sin s final).',
    explicacionHy: 'Ավարտված անցյալի եզակի 2-րդ դեմքն է «partiste» (առանց վերջին s-ի)։',
  },

  // 10. Reconocer verbos en textos breves (escuela, familia, viajes, deporte) (10 preguntas)
  {
    id: 'ctx_1',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre la ESCUELA: "¿Qué tiempo tiene el verbo destacado: Cuando sonó el timbre, los alumnos ya HABÍAN PARTIDO hacia el patio?"',
    enunciadoHy: 'ԴՊՐՈՑԻ մասին տեքստում․ «Ի՞նչ ժամանակաձև ունի ընդգծված բայը՝ Cuando sonó el timbre, los alumnos ya HABÍAN PARTIDO hacia el patio?»',
    contextoTextoEs: 'En el colegio, la campana marca los recreos. Cuando sonó el timbre, los alumnos ya habían partido hacia el patio para jugar.',
    contextoTextoHy: 'Դպրոցում զանգն ազդարարում է դասամիջոցները։ Երբ զանգը հնչեց, աշակերտներն արդեն մեկնել էին դեպի բակ՝ խաղալու։',
    opciones: [
      'Pretérito pluscuamperfecto de indicativo',
      'Pretérito perfecto compuesto de indicativo',
      'Pretérito anterior de indicativo',
      'Condicional perfecto de indicativo'
    ],
    respuestaCorrecta: 'Pretérito pluscuamperfecto de indicativo',
    explicacionEs: '"Habían partido" expresa una acción pasada anterior a otra acción pasada ("sonó").',
    explicacionHy: '«Habían partido»-ն արտահայտում է անցյալ գործողություն մեկ այլ անցյալից («sonó») առաջ։',
  },
  {
    id: 'ctx_2',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre la FAMILIA: "¿Qué modo tiene el verbo: Quiero que mi hermano AME la lectura tanto como yo?"',
    enunciadoHy: 'ԸՆՏԱՆԻՔԻ մասին տեքստում․ «Ի՞նչ եղանակ ունի բայը՝ Quiero que mi hermano AME la lectura tanto como yo?»',
    contextoTextoEs: 'En nuestra familia leemos juntos cada noche. Quiero que mi hermano ame la lectura tanto como yo.',
    contextoTextoHy: 'Մեր ընտանիքում ամեն երեկո միասին կարդում ենք։ Ուզում եմ, որ եղբայրս սիրի ընթերցանությունը այնքան, որքան ես։',
    opciones: [
      'Modo subjuntivo (presente)',
      'Modo indicativo (presente)',
      'Modo imperativo',
      'Forma no personal'
    ],
    respuestaCorrecta: 'Modo subjuntivo (presente)',
    explicacionEs: 'Depende de un verbo de deseo ("quiero que..."), por lo que exige modo subjuntivo ("ame").',
    explicacionHy: 'Կախված է ցանկություն արտահայտող բայից («quiero que...»), ուստի պահանջում է ըղձական եղանակ («ame»)։',
  },
  {
    id: 'ctx_3',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre VIAJES: "¿A qué verbo pertenece FUI en: El verano pasado FUI guía turístico en Madrid?"',
    enunciadoHy: 'ՃԱՄՓՈՐԴՈՒԹՅԱՆ մասին տեքստում․ «Ո՞ր բային է պատկանում FUI-ն՝ El verano pasado FUI guía turístico en Madrid?»',
    contextoTextoEs: 'El verano pasado fui guía turístico en Madrid para ayudar a los viajeros.',
    contextoTextoHy: 'Անցյալ ամառ ես զբոսաշրջային էքսկուրսավար էի Մադրիդում՝ ճանապարհորդներին օգնելու համար։',
    opciones: [
      'Al verbo SER (identidad o profesión en el pasado)',
      'Al verbo IR (desplazamiento físico)',
      'Al verbo ESTAR',
      'Al verbo TENER'
    ],
    respuestaCorrecta: 'Al verbo SER (identidad o profesión en el pasado)',
    explicacionEs: 'Indica una profesión o rol ("guía turístico"), por tanto pertenece al verbo SER.',
    explicacionHy: 'Նշում է մասնագիտություն կամ դեր («էքսկուրսավար էի»), ուստի SER բայն է։',
  },
  {
    id: 'ctx_4',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre VIAJES: "¿A qué verbo pertenece FUI en: A las seis de la mañana FUI a la estación de trenes?"',
    enunciadoHy: 'ՃԱՄՓՈՐԴՈՒԹՅԱՆ մասին տեքստում․ «Ո՞ր բային է պատկանում FUI-ն՝ A las seis de la mañana FUI a la estación de trenes?»',
    contextoTextoEs: 'A las seis de la mañana fui a la estación de trenes para tomar el primer tren.',
    contextoTextoHy: 'Առավոտյան ժամը վեցին ես գնացի գնացքների կայարան՝ առաջին գնացքը նստելու համար։',
    opciones: [
      'Al verbo IR (movimiento hacia un lugar con "a")',
      'Al verbo SER',
      'Al verbo HABER',
      'Al verbo PARTIR'
    ],
    respuestaCorrecta: 'Al verbo IR (movimiento hacia un lugar con "a")',
    explicacionEs: 'Va seguido de la preposición "a" y un destino ("la estación"), por lo que es el verbo IR.',
    explicacionHy: 'Հաջորդում է «a» նախդիրը և ուղղությունը («կայարան»), ուստի IR բայն է։',
  },
  {
    id: 'ctx_5',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre DEPORTE: "¿Qué tiempo tiene TEMÍAMOS en: Durante el partido final TEMÍAMOS perder la copa?"',
    enunciadoHy: 'ՍՊՈՐՏԻ մասին տեքստում․ «Ի՞նչ ժամանակաձև ունի TEMÍAMOS-ը՝ Durante el partido final TEMÍAMOS perder la copa?»',
    contextoTextoEs: 'Durante el partido final temíamos perder la copa, pero al final ganamos con orgullo.',
    contextoTextoHy: 'Եզրափակիչ խաղի ժամանակ մենք վախենում էինք կորցնել գավաթը, բայց ի վերջո հպարտությամբ հաղթեցինք։',
    opciones: [
      'Pretérito imperfecto de indicativo',
      'Condicional simple de indicativo',
      'Pretérito perfecto simple de indicativo',
      'Pretérito imperfecto de subjuntivo'
    ],
    respuestaCorrecta: 'Pretérito imperfecto de indicativo',
    explicacionEs: '"Temíamos" describe un estado continuo o emoción prolongada en el pasado: imperfecto de indicativo.',
    explicacionHy: '«Temíamos»-ը նկարագրում է անցյալի տևական հոգեվիճակ՝ սահմանական անկատար անցյալ։',
  },
  {
    id: 'ctx_6',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre la ESCUELA: "¿Qué valor tiene el verbo SÉ en: SÉ responsable con tus deberes de matemáticas?"',
    enunciadoHy: 'ԴՊՐՈՑԻ մասին տեքստում․ «Ի՞նչ արժեք ունի SÉ բայը՝ SÉ responsable con tus deberes de matemáticas?»',
    contextoTextoEs: 'El tutor nos aconsejó: «Sé responsable con tus deberes de matemáticas si quieres aprobar».',
    contextoTextoHy: 'Դասղեկը մեզ խորհուրդ տվեց․ «Եղի՛ր պատասխանատու մաթեմատիկայի տնայինների հետ, եթե ուզում ես հանձնել»։',
    opciones: [
      'Imperativo afirmativo (tú) del verbo ser',
      'Presente de indicativo (yo sé de saber)',
      'Pretérito perfecto simple',
      'Pronombre reflexivo'
    ],
    respuestaCorrecta: 'Imperativo afirmativo (tú) del verbo ser',
    explicacionEs: 'Es una orden o consejo directo ("¡Sé responsable!"), imperativo de tú del verbo ser.',
    explicacionHy: 'Ուղիղ խորհուրդ կամ հրաման է («Եղի՛ր պատասխանատու»), ser բայի tú դեմքի հրամայականը։',
  },
  {
    id: 'ctx_7',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre DEPORTE: "¿Qué persona y número tiene ENTRENÁBAMOS y PARTÍAMOS?"',
    enunciadoHy: 'ՍՊՈՐՏԻ մասին տեքստում․ «Ի՞նչ դեմք և թիվ ունեն ENTRENÁBAMOS և PARTÍAMOS բայերը»։',
    contextoTextoEs: 'Cada sábado mis compañeros y yo entrenábamos temprano y partíamos juntos al estadio.',
    contextoTextoHy: 'Ամեն շաբաթ իմ ընկերներն ու ես վաղ մարզվում էինք և միասին մեկնում մարզադաշտ։',
    opciones: [
      '1.ª persona del plural (nosotros/as)',
      '2.ª persona del plural (vosotros/as)',
      '3.ª persona del plural (ellos/as)',
      '1.ª persona del singular (yo)'
    ],
    respuestaCorrecta: '1.ª persona del plural (nosotros/as)',
    explicacionEs: 'El sujeto es "mis compañeros y yo" = nosotros, y la desinencia es "-mos" (1.ª persona plural).',
    explicacionHy: 'Ենթական «իմ ընկերներն ու ես» = մենք (nosotros), իսկ վերջավորությունը՝ «-mos» (հոգնակի 1-ին դեմք)։',
  },
  {
    id: 'ctx_8',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre la FAMILIA: "¿Qué tiempo tiene HE TEMIDO en: Esta tarde HE TEMIDO que la abuela no viniera?"',
    enunciadoHy: 'ԸՆՏԱՆԻՔԻ մասին տեքստում․ «Ի՞նչ ժամանակաձև ունի HE TEMIDO-ն՝ Esta tarde HE TEMIDO que la abuela no viniera?»',
    contextoTextoEs: 'Esperábamos a la abuela para cenar. Esta tarde he temido que no viniera por la lluvia.',
    contextoTextoHy: 'Տատիկին էինք սպասում ընթրիքին։ Այսօր կեսօրին ես վախեցել եմ, որ նա անձրևի պատճառով չի գա։',
    opciones: [
      'Pretérito perfecto compuesto de indicativo',
      'Pretérito pluscuamperfecto de indicativo',
      'Pretérito anterior de indicativo',
      'Presente de indicativo'
    ],
    respuestaCorrecta: 'Pretérito perfecto compuesto de indicativo',
    explicacionEs: '"He temido" está en pretérito perfecto compuesto, ligado al tiempo presente de hoy ("esta tarde").',
    explicacionHy: '«He temido»-ն սահմանական վաղակատար ներկան է՝ կապված ներկա օրվա հետ («esta tarde»)։',
  },
  {
    id: 'ctx_9',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre VIAJES: "¿Qué tiempo tiene MAÑANA PARTIREMOS hacia la montaña?"',
    enunciadoHy: 'ՃԱՄՓՈՐԴՈՒԹՅԱՆ մասին տեքստում․ «Ի՞նչ ժամանակաձև ունի MAÑANA PARTIREMOS hacia la montaña նախադասության բայը»։',
    contextoTextoEs: 'Las mochilas están listas. Mañana partiremos hacia la montaña muy temprano.',
    contextoTextoHy: 'Ուսապարկերը պատրաստ են։ Վաղը շատ վաղ կմեկնենք դեպի լեռներ։',
    opciones: [
      'Futuro simple de indicativo',
      'Presente de indicativo',
      'Condicional simple de indicativo',
      'Futuro simple de subjuntivo'
    ],
    respuestaCorrecta: 'Futuro simple de indicativo',
    explicacionEs: '"Partiremos" expresa una acción venidera con el infinitivo partir + -emos.',
    explicacionHy: '«Partiremos»-ն արտահայտում է ապագա գործողություն՝ partir + -emos։',
  },
  {
    id: 'ctx_10',
    categoria: 'contexto',
    categoriaEs: '10. Textos y contexto',
    categoriaHy: '10. Տեքստեր և համատեքստ',
    enunciadoEs: 'En el texto sobre DEPORTE: "¿Qué modo y tiempo tiene SI EL EQUIPO GANARA mañana, celebraríamos en la plaza?"',
    enunciadoHy: 'ՍՊՈՐՏԻ մասին տեքստում․ «Ի՞նչ եղանակ և ժամանակ ունի SI EL EQUIPO GANARA mañana... նախադասության GANARA բայը»։',
    contextoTextoEs: 'Todos estamos ilusionados. Si el equipo ganara mañana el trofeo, celebraríamos en la plaza.',
    contextoTextoHy: 'Բոլորս ոգևորված ենք։ Եթե թիմը վաղը շահեր գավաթը, կտոնեինք հրապարակում։',
    opciones: [
      'Pretérito imperfecto de subjuntivo',
      'Futuro simple de indicativo',
      'Condicional simple de indicativo',
      'Pretérito perfecto simple de indicativo'
    ],
    respuestaCorrecta: 'Pretérito imperfecto de subjuntivo',
    explicacionEs: 'En la condición hipotética con "si" sobre el futuro se emplea el pretérito imperfecto de subjuntivo ("ganara").',
    explicacionHy: 'Ապագային վերաբերող ենթադրական պայմանում գործածվում է ըղձական անկատար անցյալը («ganara»)։',
  },
];
