/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Question } from './types';

export const QUESTIONS_PART_1: Question[] = [
  // 1. Identificar el tiempo y el modo (10 preguntas)
  {
    id: 'tm_1',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo verbal corresponde a la forma "amábamos"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «amábamos» բայաձևը։',
    opciones: [
      'Pretérito imperfecto de indicativo',
      'Condicional simple de indicativo',
      'Pretérito imperfecto de subjuntivo',
      'Presente de indicativo'
    ],
    respuestaCorrecta: 'Pretérito imperfecto de indicativo',
    explicacionEs: 'El sufijo "-ba-" en la primera conjugación (-ar) es característico del pretérito imperfecto de indicativo.',
    explicacionHy: 'Առաջին խոնարհման (-ar) մեջ «-ba-» մասնիկը բնորոշ է սահմանական եղանակի անկատար անցյալին։',
  },
  {
    id: 'tm_2',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo representa la forma "temieras"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «temieras» բայաձևը։',
    opciones: [
      'Pretérito imperfecto de subjuntivo',
      'Futuro simple de indicativo',
      'Pretérito pluscuamperfecto de indicativo',
      'Condicional simple de indicativo'
    ],
    respuestaCorrecta: 'Pretérito imperfecto de subjuntivo',
    explicacionEs: 'La terminación "-ra" (o "-se") corresponde al pretérito imperfecto de subjuntivo.',
    explicacionHy: '«-ra» (կամ «-se») վերջավորությունը պատկանում է ըղձական եղանակի անկատար անցյալին։',
  },
  {
    id: 'tm_3',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿A qué tiempo y modo pertenece "partiré"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «partiré» բայաձևը։',
    opciones: [
      'Futuro simple de indicativo',
      'Futuro simple de subjuntivo',
      'Condicional simple de indicativo',
      'Pretérito perfecto simple de indicativo'
    ],
    respuestaCorrecta: 'Futuro simple de indicativo',
    explicacionEs: '"Partiré" lleva tilde en la -é y se forma sobre el infinitivo: es futuro simple de indicativo.',
    explicacionHy: '«Partiré»-ն ունի շեշտ -é-ի վրա և կազմվում է անորոշ ձևից՝ սահմանական պարզ ապառնի է։',
  },
  {
    id: 'tm_4',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿A qué tiempo y modo pertenece "hubo temido"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «hubo temido» բայաձևը։',
    opciones: [
      'Pretérito anterior de indicativo',
      'Pretérito pluscuamperfecto de indicativo',
      'Condicional perfecto de indicativo',
      'Pretérito perfecto compuesto de indicativo'
    ],
    respuestaCorrecta: 'Pretérito anterior de indicativo',
    explicacionEs: 'El verbo auxiliar "hubo" está en pretérito perfecto simple de indicativo, por lo que forma el pretérito anterior.',
    explicacionHy: '«Hubo» օժանդակ բայը դրված է ավարտված անցյալով, հետևաբար կազմում է pretérito anterior։',
  },
  {
    id: 'tm_5',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo es "hayan partido"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «hayan partido» բայաձևը։',
    opciones: [
      'Pretérito perfecto compuesto de subjuntivo',
      'Pretérito pluscuamperfecto de subjuntivo',
      'Futuro perfecto de subjuntivo',
      'Pretérito perfecto compuesto de indicativo'
    ],
    respuestaCorrecta: 'Pretérito perfecto compuesto de subjuntivo',
    explicacionEs: '"Hayan" es el presente de subjuntivo de haber; con el participio forma el pretérito perfecto compuesto de subjuntivo.',
    explicacionHy: '«Hayan»-ը haber-ի ըղձական ներկան է․ participio-ի հետ կազմում է pretérito perfecto compuesto de subjuntivo։',
  },
  {
    id: 'tm_6',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo es "sería"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «sería» բայաձևը։',
    opciones: [
      'Condicional simple de indicativo',
      'Pretérito imperfecto de indicativo',
      'Pretérito imperfecto de subjuntivo',
      'Futuro simple de indicativo'
    ],
    respuestaCorrecta: 'Condicional simple de indicativo',
    explicacionEs: '"Sería" tiene desinencia -ía sobre el infinitivo: condicional simple de indicativo.',
    explicacionHy: '«Sería»-ն ունի -ía վերջավորություն անորոշի հիման վրա՝ սահմանական պարզ պայմանական է։',
  },
  {
    id: 'tm_7',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo es "amare" (sin tilde)?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «amare» բայաձևը (առանց շեշտի)։',
    opciones: [
      'Futuro simple de subjuntivo',
      'Futuro simple de indicativo',
      'Presente de subjuntivo',
      'Condicional simple de indicativo'
    ],
    respuestaCorrecta: 'Futuro simple de subjuntivo',
    explicacionEs: '"Amare" sin tilde es futuro simple de subjuntivo; con tilde (amaré) es futuro simple de indicativo.',
    explicacionHy: '«Amare»-ն առանց շեշտի ըղձական պարզ ապառնի է, իսկ շեշտով (amaré)՝ սահմանական ապառնի։',
  },
  {
    id: 'tm_8',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo es "hubieseis sido"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «hubieseis sido» բայաձևը։',
    opciones: [
      'Pretérito pluscuamperfecto de subjuntivo',
      'Pretérito anterior de indicativo',
      'Pretérito pluscuamperfecto de indicativo',
      'Futuro perfecto de subjuntivo'
    ],
    respuestaCorrecta: 'Pretérito pluscuamperfecto de subjuntivo',
    explicacionEs: '"Hubieseis" pertenece a la serie -se del pretérito pluscuamperfecto de subjuntivo.',
    explicacionHy: '«Hubieseis»-ը պատկանում է ըղձական վաղակատար անցյալի -se շարքին։',
  },
  {
    id: 'tm_9',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué forma y modo es "sed" en "¡Sed sinceros!"?',
    enunciadoHy: 'Ի՞նչ ձևի և եղանակի է պատկանում «sed»-ը «¡Sed sinceros!» արտահայտության մեջ։',
    opciones: [
      'Imperativo afirmativo (vosotros)',
      'Presente de indicativo (yo)',
      'Pretérito perfecto simple (tú)',
      'Presente de subjuntivo (vosotros)'
    ],
    respuestaCorrecta: 'Imperativo afirmativo (vosotros)',
    explicacionEs: '"Sed" es la forma de imperativo afirmativo para la segunda persona del plural (vosotros) del verbo ser.',
    explicacionHy: '«Sed»-ը ser բայի vosotros դեմքի հաստատական հրամայականն է։',
  },
  {
    id: 'tm_10',
    categoria: 'tiempo_modo',
    categoriaEs: '1. Tiempo y modo',
    categoriaHy: '1. Ժամանակաձև և եղանակ',
    enunciadoEs: '¿Qué tiempo y modo es "habías temido"?',
    enunciadoHy: 'Ի՞նչ ժամանակաձևի և եղանակի է պատկանում «habías temido» բայաձևը։',
    opciones: [
      'Pretérito pluscuamperfecto de indicativo',
      'Pretérito perfecto compuesto de indicativo',
      'Condicional perfecto de indicativo',
      'Pretérito pluscuamperfecto de subjuntivo'
    ],
    respuestaCorrecta: 'Pretérito pluscuamperfecto de indicativo',
    explicacionEs: '"Habías" es pretérito imperfecto de indicativo de haber; con el participio forma el pretérito pluscuamperfecto de indicativo.',
    explicacionHy: '«Habías»-ը haber-ի անկատար անցյալն է․ participio-ի հետ կազմում է pretérito pluscuamperfecto de indicativo։',
  },

  // 2. Identificar persona y número (10 preguntas)
  {
    id: 'pn_1',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿A qué persona y número corresponde la forma "temisteis"?',
    enunciadoHy: 'Ո՞ր դեմքին և թվին է համապատասխանում «temisteis» բայաձևը։',
    opciones: [
      '2.ª persona del plural',
      '1.ª persona del plural',
      '3.ª persona del plural',
      '2.ª persona del singular'
    ],
    respuestaCorrecta: '2.ª persona del plural',
    explicacionEs: 'La desinencia "-steis" identifica de forma inequívoca a vosotros/as (2.ª persona del plural).',
    explicacionHy: '«-steis» վերջավորությունը միանշանակ ցույց է տալիս vosotros/as-ը (հոգնակի 2-րդ դեմք)։',
  },
  {
    id: 'pn_2',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: 'Cuando decimos "Ustedes parten", ¿en qué persona gramatical está el verbo?',
    enunciadoHy: 'Երբ ասում ենք «Ustedes parten», ո՞ր քերականական դեմքով է դրված բայը։',
    opciones: [
      '3.ª persona del plural',
      '2.ª persona del plural',
      '1.ª persona del plural',
      '3.ª persona del singular'
    ],
    respuestaCorrecta: '3.ª persona del plural',
    explicacionEs: 'Aunque "ustedes" alude a los interlocutores, sintácticamente exige verbo en 3.ª persona del plural.',
    explicacionHy: 'Թեև «ustedes»-ը վերաբերում է զրուցակիցներին, շարահյուսորեն պահանջում է հոգնակի 3-րդ դեմք։',
  },
  {
    id: 'pn_3',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿A qué persona y número corresponde "sois"?',
    enunciadoHy: 'Ո՞ր դեմքին և թվին է համապատասխանում «sois» բայաձևը։',
    opciones: [
      '2.ª persona del plural (vosotros)',
      '1.ª persona del singular (yo)',
      '3.ª persona del plural (ellos)',
      '2.ª persona del singular (tú)'
    ],
    respuestaCorrecta: '2.ª persona del plural (vosotros)',
    explicacionEs: '"Sois" es la forma de presente de indicativo del verbo ser para vosotros/vosotras.',
    explicacionHy: '«Sois»-ը ser բայի vosotros/as դեմքի սահմանական ներկա ձևն է։',
  },
  {
    id: 'pn_4',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿A qué persona y número corresponde "partimos"?',
    enunciadoHy: 'Ո՞ր դեմքին և թվին է համապատասխանում «partimos» բայաձևը։',
    opciones: [
      '1.ª persona del plural (nosotros/as)',
      '2.ª persona del plural (vosotros/as)',
      '3.ª persona del plural (ellos/as)',
      '1.ª persona del singular (yo)'
    ],
    respuestaCorrecta: '1.ª persona del plural (nosotros/as)',
    explicacionEs: 'La desinencia "-mos" siempre señala la 1.ª persona del plural (nosotros/nosotras).',
    explicacionHy: '«-mos» վերջավորությունը միշտ ցույց է տալիս հոգնակի 1-ին դեմքը (nosotros/as)։',
  },
  {
    id: 'pn_5',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿Qué persona y número tiene "era" en la oración: "Yo era feliz"?',
    enunciadoHy: 'Ի՞նչ դեմք և թիվ ունի «era» բայը «Yo era feliz» նախադասության մեջ։',
    opciones: [
      '1.ª persona del singular',
      '3.ª persona del singular',
      '2.ª persona del singular',
      '1.ª persona del plural'
    ],
    respuestaCorrecta: '1.ª persona del singular',
    explicacionEs: 'En esta oración el sujeto explícito es "Yo", por tanto es 1.ª persona del singular.',
    explicacionHy: 'Այս նախադասության մեջ ենթական «Yo»-ն է, ուստի եզակի 1-ին դեմք է։',
  },
  {
    id: 'pn_6',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿A qué persona y número corresponde "amas"?',
    enunciadoHy: 'Ո՞ր դեմքին և թվին է համապատասխանում «amas» բայաձևը։',
    opciones: [
      '2.ª persona del singular (tú)',
      '3.ª persona del singular (él/ella)',
      '1.ª persona del singular (yo)',
      '2.ª persona del plural (vosotros)'
    ],
    respuestaCorrecta: '2.ª persona del singular (tú)',
    explicacionEs: 'La desinencia "-s" indica 2.ª persona del singular (tú).',
    explicacionHy: '«-s» վերջավորությունը ցույց է տալիս եզակի 2-րդ դեմքը (tú)։',
  },
  {
    id: 'pn_7',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿Qué persona y número representa "hubieron temido"?',
    enunciadoHy: 'Ի՞նչ դեմք և թիվ է ներկայացնում «hubieron temido» բայաձևը։',
    opciones: [
      '3.ª persona del plural (ellos/ellas/ustedes)',
      '1.ª persona del plural (nosotros/as)',
      '2.ª persona del plural (vosotros/as)',
      '3.ª persona del singular (él/ella)'
    ],
    respuestaCorrecta: '3.ª persona del plural (ellos/ellas/ustedes)',
    explicacionEs: '"Hubieron" termina en "-ron", marca de 3.ª persona del plural.',
    explicacionHy: '«Hubieron»-ն ավարտվում է «-ron»-ով՝ հոգնակի 3-րդ դեմքի ցուցիչով։',
  },
  {
    id: 'pn_8',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿A qué persona corresponde "sé" en "¡Sé puntual!"?',
    enunciadoHy: 'Ո՞ր դեմքին է համապատասխանում «sé»-ն «¡Sé puntual!» նախադասության մեջ։',
    opciones: [
      '2.ª persona del singular (tú)',
      '1.ª persona del singular (yo)',
      '3.ª persona del singular (usted)',
      '2.ª persona del plural (vosotros)'
    ],
    respuestaCorrecta: '2.ª persona del singular (tú)',
    explicacionEs: 'En imperativo afirmativo, "sé" es la 2.ª persona del singular correspondiente a "tú".',
    explicacionHy: 'Հաստատական հրամայականում «sé»-ն «tú»-ի եզակի 2-րդ դեմքն է։',
  },
  {
    id: 'pn_9',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿Qué personas gramaticales puede admitir la forma aislada "amaba"?',
    enunciadoHy: 'Ի՞նչ քերականական դեմքեր կարող է ունենալ առանձին վերցված «amaba» ձևը։',
    opciones: [
      '1.ª y 3.ª persona del singular (yo / él, ella, usted)',
      'Solo 1.ª persona del singular (yo)',
      'Solo 3.ª persona del singular (él)',
      '2.ª y 3.ª persona del singular'
    ],
    respuestaCorrecta: '1.ª y 3.ª persona del singular (yo / él, ella, usted)',
    explicacionEs: 'Sin contexto, "amaba" coincide en la 1.ª singular (yo amaba) y la 3.ª singular (él amaba).',
    explicacionHy: 'Առանց համատեքստի «amaba»-ն համընկնում է եզակի 1-ին (yo) և 3-րդ (él/ella/usted) դեմքերում։',
  },
  {
    id: 'pn_10',
    categoria: 'persona_numero',
    categoriaEs: '2. Persona y número',
    categoriaHy: '2. Դեմք և թիվ',
    enunciadoEs: '¿Qué persona y número es "fuiste"?',
    enunciadoHy: 'Ի՞նչ դեմք և թիվ ունի «fuiste» բայաձևը։',
    opciones: [
      '2.ª persona del singular (tú)',
      '1.ª persona del singular (yo)',
      '3.ª persona del singular (él/ella)',
      '2.ª persona del plural (vosotros)'
    ],
    respuestaCorrecta: '2.ª persona del singular (tú)',
    explicacionEs: '"Fuiste" es la 2.ª persona del singular (tú) del pretérito perfecto simple de ser (o ir).',
    explicacionHy: '«Fuiste»-ն ser (կամ ir) բայի ավարտված անցյալի եզակի 2-րդ դեմքն է (tú)։',
  },

  // 3. Completar una conjugación (10 preguntas)
  {
    id: 'comp_1',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa la serie de presente de amar: amo, amas, ama, ________, amáis, aman.',
    enunciadoHy: 'Լրացրու amar-ի ներկայի շարքը՝ amo, amas, ama, ________, amáis, aman։',
    opciones: ['amamos', 'amemos', 'amáramos', 'amabais'],
    respuestaCorrecta: 'amamos',
    explicacionEs: 'La 1.ª persona del plural del presente de indicativo de amar es "amamos".',
    explicacionHy: 'Amar բայի սահմանական ներկայի հոգնակի 1-ին դեմքն է «amamos»։',
  },
  {
    id: 'comp_2',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el pretérito imperfecto de temer: temía, temías, temía, ________, temíais, temían.',
    enunciadoHy: 'Լրացրու temer-ի անկատար անցյալը՝ temía, temías, temía, ________, temíais, temían։',
    opciones: ['temíamos', 'temeríamos', 'temiéramos', 'tememos'],
    respuestaCorrecta: 'temíamos',
    explicacionEs: 'La 1.ª persona del plural del pretérito imperfecto es "temíamos", con tilde en la -í-.',
    explicacionHy: 'Անկատար անցյալի հոգնակի 1-ին դեմքն է «temíamos»՝ շեշտված -í-ով։',
  },
  {
    id: 'comp_3',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el pretérito perfecto simple de partir: partí, partiste, partió, partimos, ________, partieron.',
    enunciadoHy: 'Լրացրու partir-ի ավարտված անցյալը՝ partí, partiste, partió, partimos, ________, partieron։',
    opciones: ['partisteis', 'partíais', 'partiréis', 'partiste'],
    respuestaCorrecta: 'partisteis',
    explicacionEs: 'Para vosotros/as en el pretérito perfecto simple corresponde "partisteis".',
    explicacionHy: 'Vosotros/as դեմքի համար ավարտված անցյալում համապատասխանում է «partisteis»-ը։',
  },
  {
    id: 'comp_4',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el futuro simple de ser: seré, serás, será, seremos, ________, serán.',
    enunciadoHy: 'Լրացրու ser-ի ապառնին՝ seré, serás, será, seremos, ________, serán։',
    opciones: ['seréis', 'seríais', 'seáis', 'siendo'],
    respuestaCorrecta: 'seréis',
    explicacionEs: 'La forma de 2.ª persona del plural del futuro de ser es "seréis" (con tilde en -é-).',
    explicacionHy: 'Ser-ի ապառնու հոգնակի 2-րդ դեմքն է «seréis» (-é-ի վրա շեշտով)։',
  },
  {
    id: 'comp_5',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el presente de subjuntivo de amar: ame, ames, ame, amemos, ________, amen.',
    enunciadoHy: 'Լրացրու amar-ի ըղձական ներկան՝ ame, ames, ame, amemos, ________, amen։',
    opciones: ['améis', 'amáis', 'amasteis', 'amaseis'],
    respuestaCorrecta: 'améis',
    explicacionEs: 'En presente de subjuntivo la vocal característica es -e-: vosotros améis.',
    explicacionHy: 'Ըղձական ներկայում թեմատիկ ձայնավորը -e-ն է՝ vosotros améis։',
  },
  {
    id: 'comp_6',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el imperfecto de subjuntivo (-ra) de partir: partiera, partieras, partiera, ________, partierais, partieran.',
    enunciadoHy: 'Լրացրու partir-ի ըղձական անկատարը (-ra)՝ partiera, partieras, partiera, ________, partierais, partieran։',
    opciones: ['partiéramos', 'partiríamos', 'partiéseis', 'partiésemos'],
    respuestaCorrecta: 'partiéramos',
    explicacionEs: 'La 1.ª persona del plural lleva tilde: "partiéramos".',
    explicacionHy: 'Հոգնակի 1-ին դեմքը շեշտվում է՝ «partiéramos»։',
  },
  {
    id: 'comp_7',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el presente de indicativo de ser: soy, eres, es, somos, ________, son.',
    enunciadoHy: 'Լրացրու ser-ի սահմանական ներկան՝ soy, eres, es, somos, ________, son։',
    opciones: ['sois', 'seis', 'erais', 'seréis'],
    respuestaCorrecta: 'sois',
    explicacionEs: 'Vosotros sois es la forma de 2.ª del plural de ser en presente de indicativo.',
    explicacionHy: '«Vosotros sois»-ը ser-ի սահմանական ներկայի հոգնակի 2-րդ դեմքն է։',
  },
  {
    id: 'comp_8',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa los imperativos afirmativos de vosotros: amad, temed, partid, ________.',
    enunciadoHy: 'Լրացրու vosotros-ի հաստատական հրամայականները՝ amad, temed, partid, ________։',
    opciones: ['sed', 'sé', 'sean', 'sois'],
    respuestaCorrecta: 'sed',
    explicacionEs: 'El imperativo afirmativo de vosotros para el verbo ser es "sed".',
    explicacionHy: 'Ser բայի vosotros դեմքի հաստատական հրամայականն է «sed»։',
  },
  {
    id: 'comp_9',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el pretérito perfecto simple de ser: fui, fuiste, fue, fuimos, fuisteis, ________.',
    enunciadoHy: 'Լրացրու ser-ի ավարտված անցյալը՝ fui, fuiste, fue, fuimos, fuisteis, ________։',
    opciones: ['fueron', 'eran', 'fueran', 'serán'],
    respuestaCorrecta: 'fueron',
    explicacionEs: 'Ellos/ellas/ustedes fueron es la 3.ª persona del plural del pretérito perfecto simple.',
    explicacionHy: '«Fueron»-ը սահմանական ավարտված անցյալի հոգնակի 3-րդ դեմքն է։',
  },
  {
    id: 'comp_10',
    categoria: 'completar',
    categoriaEs: '3. Completar conjugación',
    categoriaHy: '3. Լրացնել խոնարհումը',
    enunciadoEs: 'Completa el condicional simple de temer: temería, temerías, temería, temeríamos, ________, temerían.',
    enunciadoHy: 'Լրացրու temer-ի պարզ պայմանականը՝ temería, temerías, temería, temeríamos, ________, temerían։',
    opciones: ['temeríais', 'temíais', 'temierais', 'temeréis'],
    respuestaCorrecta: 'temeríais',
    explicacionEs: 'Para vosotros en condicional simple corresponde "temeríais" (con tilde en -í-).',
    explicacionHy: 'Vosotros-ի համար պարզ պայմանականում համապատասխանում է «temeríais»-ը։',
  },

  // 4. Opción múltiple con 4 alternativas (10 preguntas)
  {
    id: 'om_1',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Cuál de los siguientes verbos es IRREGULAR en español?',
    enunciadoHy: 'Հետևյալ բայերից ո՞րն է ԱՆԿԱՆՈՆ իսպաներենում։',
    opciones: ['ser', 'amar', 'temer', 'partir'],
    respuestaCorrecta: 'ser',
    explicacionEs: 'Amar, temer y partir son modelos regulares. Ser es un verbo completamente irregular.',
    explicacionHy: 'Amar, temer և partir բայերը կանոնավոր են, իսկ ser-ը՝ անկանոն։',
  },
  {
    id: 'om_2',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿A qué conjugación pertenece el verbo "temer"?',
    enunciadoHy: 'Ո՞ր խոնարհման խմբին է պատկանում «temer» բայը։',
    opciones: [
      'Segunda conjugación (-er)',
      'Primera conjugación (-ar)',
      'Tercera conjugación (-ir)',
      'Cuarta conjugación'
    ],
    respuestaCorrecta: 'Segunda conjugación (-er)',
    explicacionEs: 'Los verbos cuyo infinitivo termina en -er pertenecen a la segunda conjugación.',
    explicacionHy: '-er վերջավորությամբ անորոշ ձև ունեցող բայերը պատկանում են երկրորդ խոնարհմանը։',
  },
  {
    id: 'om_3',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Cuál es la forma correcta del gerundio compuesto de "partir"?',
    enunciadoHy: 'Ո՞րն է «partir» բայի բաղադրյալ գերունդիոյի ճիշտ ձևը։',
    opciones: [
      'habiendo partido',
      'haber partido',
      'partiendo',
      'habiendo partiendo'
    ],
    respuestaCorrecta: 'habiendo partido',
    explicacionEs: 'El gerundio compuesto se forma con "habiendo" + participio ("habiendo partido").',
    explicacionHy: 'Բաղադրյալ գերունդիոն կազմվում է «habiendo» + participio («habiendo partido»)։',
  },
  {
    id: 'om_4',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Cómo se expresa la orden negativa para tú con el verbo "temer"?',
    enunciadoHy: 'Ինչպե՞ս է արտահայտվում «temer» բայի ժխտական հրամանը tú-ի համար։',
    opciones: ['No temas', 'No teme', 'No temas tú jamás', 'No temed'],
    respuestaCorrecta: 'No temas',
    explicacionEs: 'El imperativo negativo se forma con el presente de subjuntivo: "No temas".',
    explicacionHy: 'Ժխտական հրամայականը կազմվում է presente de subjuntivo-ով՝ «No temas»։',
  },
  {
    id: 'om_5',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Qué elemento representa la letra "Vt" en el análisis morfológico de "tem-e-r"?',
    enunciadoHy: 'Ի՞նչ տարր է ներկայացնում «Vt» հապավումը «tem-e-r»-ի ձևաբանական վերլուծության մեջ։',
    opciones: [
      'Vocal temática',
      'Verbo transitivo',
      'Variación temporal',
      'Vocal terminativa'
    ],
    respuestaCorrecta: 'Vocal temática',
    explicacionEs: 'Vt significa "Vocal temática", que indica la conjugación del verbo.',
    explicacionHy: 'Vt նշանակում է «Թեմատիկ ձայնավոր» (Vocal temática)՝ ցույց տալով խոնարհման խումբը։',
  },
  {
    id: 'om_6',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Cuál es el imperativo afirmativo de tú para el verbo "ser"?',
    enunciadoHy: 'Ո՞րն է «ser» բայի tú դեմքի հաստատական հրամայականը։',
    opciones: ['sé', 'se', 'sea', 'sed'],
    respuestaCorrecta: 'sé',
    explicacionEs: 'El imperativo afirmativo es "sé" (con tilde diacrítica), para distinguirlo del pronombre "se".',
    explicacionHy: 'Հաստատական հրամայականն է «sé»-ն (շեշտով)՝ «se» դերանունից տարբերելու համար։',
  },
  {
    id: 'om_7',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Qué expresa el modo subjuntivo?',
    enunciadoHy: 'Ի՞նչ է արտահայտում ըղձական եղանակը (subjuntivo)։',
    opciones: [
      'Deseos, dudas y situaciones hipotéticas',
      'Hechos reales comprobados y objetivos',
      'Órdenes y mandatos directos exclusivamente',
      'Acciones pasadas definitivas'
    ],
    respuestaCorrecta: 'Deseos, dudas y situaciones hipotéticas',
    explicacionEs: 'El subjuntivo expresa el plano subjetivo: deseos, dudas, valoraciones e hipótesis.',
    explicacionHy: 'Ըղձական եղանակն արտահայտում է ցանկություն, կասկած, գնահատական և ենթադրություն։',
  },
  {
    id: 'om_8',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: '¿Cuál es el participio del verbo "ser"?',
    enunciadoHy: 'Ո՞րն է «ser» բայի participio-ն (դերբայը)։',
    opciones: ['sido', 'siendo', 'sero', 'siente'],
    respuestaCorrecta: 'sido',
    explicacionEs: 'El participio de ser es "sido" (invariable con el verbo auxiliar haber).',
    explicacionHy: 'Ser-ի դերբայը (participio) «sido»-ն է։',
  },
  {
    id: 'om_9',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: 'En "Ayer fui al cine", ¿a qué verbo pertenece "fui"?',
    enunciadoHy: '«Ayer fui al cine» նախադասության մեջ ո՞ր բային է պատկանում «fui»-ն։',
    opciones: ['Al verbo ir', 'Al verbo ser', 'Al verbo hacer', 'Al verbo estar'],
    respuestaCorrecta: 'Al verbo ir',
    explicacionEs: 'Indica movimiento hacia un lugar ("al cine"), por tanto pertenece al verbo ir.',
    explicacionHy: 'Ցույց է տալիս տեղաշարժ («դեպի կինո»), ուստի ir բայն է։',
  },
  {
    id: 'om_10',
    categoria: 'opcion_multiple',
    categoriaEs: '4. Opción múltiple',
    categoriaHy: '4. Ընտրել տարբերակը',
    enunciadoEs: 'En "Fui el mejor estudiante de la clase", ¿a qué verbo pertenece "fui"?',
    enunciadoHy: '«Fui el mejor estudiante...» նախադասության մեջ ո՞ր բային է պատկանում «fui»-ն։',
    opciones: ['Al verbo ser', 'Al verbo ir', 'Al verbo tener', 'Al verbo estar'],
    respuestaCorrecta: 'Al verbo ser',
    explicacionEs: 'Expresa una cualidad o identidad personal, por lo que pertenece al verbo ser.',
    explicacionHy: 'Արտահայտում է անձնական հատկանիշ կամ ինքնություն, ուստի ser բայն է։',
  },

  // 5. Relacionar formas verbales con sus nombres (10 preguntas)
  {
    id: 'rel_1',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre gramatical le corresponde a la forma "amaste"?',
    enunciadoHy: 'Ի՞նչ քերականական անվանում է համապատասխանում «amaste» բայաձևին։',
    opciones: [
      'Pretérito perfecto simple de indicativo',
      'Pretérito imperfecto de indicativo',
      'Presente de subjuntivo',
      'Futuro simple de indicativo'
    ],
    respuestaCorrecta: 'Pretérito perfecto simple de indicativo',
    explicacionEs: '"Amaste" es la 2.ª persona del singular del pretérito perfecto simple (indefinido).',
    explicacionHy: '«Amaste»-ն ավարտված անցյալի եզակի 2-րդ դեմքն է։',
  },
  {
    id: 'rel_2',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a "habríais partido"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «habríais partido» բայաձևին։',
    opciones: [
      'Condicional perfecto de indicativo',
      'Pretérito pluscuamperfecto de indicativo',
      'Futuro perfecto de indicativo',
      'Pretérito pluscuamperfecto de subjuntivo'
    ],
    respuestaCorrecta: 'Condicional perfecto de indicativo',
    explicacionEs: '"Habríais" es el condicional simple de haber, por lo que forma el condicional perfecto.',
    explicacionHy: '«Habríais»-ը haber-ի պայմանականն է․ կազմում է condicional perfecto։',
  },
  {
    id: 'rel_3',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a la forma "amásemos"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «amásemos» բայաձևին։',
    opciones: [
      'Pretérito imperfecto de subjuntivo (-se)',
      'Pretérito imperfecto de indicativo',
      'Condicional simple de indicativo',
      'Futuro simple de subjuntivo'
    ],
    respuestaCorrecta: 'Pretérito imperfecto de subjuntivo (-se)',
    explicacionEs: 'Pertenece a la serie -se del pretérito imperfecto de subjuntivo (nosotros amásemos).',
    explicacionHy: 'Պատկանում է ըղձական անկատար անցյալի -se շարքին (nosotros amásemos)։',
  },
  {
    id: 'rel_4',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre gramatical le corresponde a "habiendo sido"?',
    enunciadoHy: 'Ի՞նչ քերականական անվանում է համապատասխանում «habiendo sido» ձևին։',
    opciones: [
      'Gerundio compuesto',
      'Infinitivo compuesto',
      'Participio pasivo',
      'Gerundio simple'
    ],
    respuestaCorrecta: 'Gerundio compuesto',
    explicacionEs: '"Habiendo" + participio ("sido") constituye el gerundio compuesto.',
    explicacionHy: '«Habiendo» + participio («sido») կազմում է բաղադրյալ գերունդիոն։',
  },
  {
    id: 'rel_5',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre gramatical le corresponde a la forma "hubiere temido"?',
    enunciadoHy: 'Ի՞նչ քերականական անվանում է համապատասխանում «hubiere temido» ձևին։',
    opciones: [
      'Futuro perfecto de subjuntivo',
      'Futuro perfecto de indicativo',
      'Pretérito anterior de indicativo',
      'Pretérito pluscuamperfecto de subjuntivo'
    ],
    respuestaCorrecta: 'Futuro perfecto de subjuntivo',
    explicacionEs: '"Hubiere" es futuro de subjuntivo de haber: forma el futuro perfecto de subjuntivo.',
    explicacionHy: '«Hubiere»-ն haber-ի ըղձական ապառնին է․ կազմում է futuro perfecto de subjuntivo։',
  },
  {
    id: 'rel_6',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a la forma "amad"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «amad» բայաձևին։',
    opciones: [
      'Imperativo afirmativo (vosotros)',
      'Participio pasivo',
      'Presente de indicativo (vosotros)',
      'Pretérito perfecto simple (yo)'
    ],
    respuestaCorrecta: 'Imperativo afirmativo (vosotros)',
    explicacionEs: 'Termina en -d: es el imperativo afirmativo de 2.ª persona del plural (vosotros).',
    explicacionHy: 'Ավարտվում է -d-ով՝ vosotros դեմքի հաստատական հրամայականն է։',
  },
  {
    id: 'rel_7',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a "temiere"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «temiere» բայաձևին։',
    opciones: [
      'Futuro simple de subjuntivo',
      'Futuro simple de indicativo',
      'Condicional simple de indicativo',
      'Presente de subjuntivo'
    ],
    respuestaCorrecta: 'Futuro simple de subjuntivo',
    explicacionEs: '"Temiere" es la forma de futuro simple de subjuntivo de temer.',
    explicacionHy: '«Temiere»-ն temer բայի ըղձական պարզ ապառնին է։',
  },
  {
    id: 'rel_8',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a "partiríais"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «partiríais» բայաձևին։',
    opciones: [
      'Condicional simple de indicativo',
      'Futuro simple de indicativo',
      'Pretérito imperfecto de subjuntivo',
      'Pretérito imperfecto de indicativo'
    ],
    respuestaCorrecta: 'Condicional simple de indicativo',
    explicacionEs: 'Formada sobre el infinitivo con desinencia -íais: condicional simple de indicativo.',
    explicacionHy: 'Կազմված է անորոշից -íais վերջավորությամբ՝ պարզ պայմանական է։',
  },
  {
    id: 'rel_9',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a "hayas amado"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «hayas amado» բայաձևին։',
    opciones: [
      'Pretérito perfecto de subjuntivo',
      'Pretérito pluscuamperfecto de subjuntivo',
      'Pretérito perfecto compuesto de indicativo',
      'Futuro perfecto de subjuntivo'
    ],
    respuestaCorrecta: 'Pretérito perfecto de subjuntivo',
    explicacionEs: '"Hayas" es presente de subjuntivo: forma el pretérito perfecto de subjuntivo.',
    explicacionHy: '«Hayas»-ը ըղձական ներկան է․ կազմում է pretérito perfecto de subjuntivo։',
  },
  {
    id: 'rel_10',
    categoria: 'relacionar',
    categoriaEs: '5. Relacionar formas',
    categoriaHy: '5. Համապատասխանեցնել ձևերը',
    enunciadoEs: '¿Qué nombre le corresponde a la forma "fuese"?',
    enunciadoHy: 'Ի՞նչ անվանում է համապատասխանում «fuese» բայաձևին։',
    opciones: [
      'Pretérito imperfecto de subjuntivo (serie -se)',
      'Pretérito perfecto simple de indicativo',
      'Futuro simple de subjuntivo',
      'Condicional simple de indicativo'
    ],
    respuestaCorrecta: 'Pretérito imperfecto de subjuntivo (serie -se)',
    explicacionEs: '"Fuese" es la serie -se del pretérito imperfecto de subjuntivo de ser (o ir).',
    explicacionHy: '«Fuese»-ն ser (կամ ir) բայի ըղձական անկատար անցյալի -se շարքն է։',
  },
];
